#
# Module manifest for module 'Microsoft.Graph.Applications'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/10/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.Applications.psm1'

# Version number of this module.
ModuleVersion = '2.38.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '467f54f2-44a8-4993-8e75-b96c3e443098'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.38.1'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.Applications.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.Applications.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgApplicationKey', 'Add-MgApplicationPassword', 
               'Add-MgServicePrincipalKey', 'Add-MgServicePrincipalPassword', 
               'Add-MgServicePrincipalTokenSigningCertificate', 
               'Clear-MgApplicationVerifiedPublisher', 
               'Confirm-MgApplicationMemberGroup', 
               'Confirm-MgApplicationMemberObject', 
               'Confirm-MgServicePrincipalMemberGroup', 
               'Confirm-MgServicePrincipalMemberObject', 
               'Find-MgApplicationSynchronizationJobSchemaDirectory', 
               'Find-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Find-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Find-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgApplication', 'Get-MgApplicationAppManagementPolicy', 
               'Get-MgApplicationAppManagementPolicyByRef', 
               'Get-MgApplicationAppManagementPolicyCount', 
               'Get-MgApplicationByAppId', 'Get-MgApplicationById', 
               'Get-MgApplicationByUniqueName', 'Get-MgApplicationCount', 
               'Get-MgApplicationCreatedOnBehalfOf', 'Get-MgApplicationDelta', 
               'Get-MgApplicationExtensionProperty', 
               'Get-MgApplicationExtensionPropertyCount', 
               'Get-MgApplicationFederatedIdentityCredential', 
               'Get-MgApplicationFederatedIdentityCredentialByName', 
               'Get-MgApplicationFederatedIdentityCredentialCount', 
               'Get-MgApplicationHomeRealmDiscoveryPolicy', 
               'Get-MgApplicationHomeRealmDiscoveryPolicyCount', 
               'Get-MgApplicationLogo', 'Get-MgApplicationMemberGroup', 
               'Get-MgApplicationMemberObject', 'Get-MgApplicationOwner', 
               'Get-MgApplicationOwnerAsAppRoleAssignment', 
               'Get-MgApplicationOwnerAsEndpoint', 
               'Get-MgApplicationOwnerAsServicePrincipal', 
               'Get-MgApplicationOwnerAsUser', 'Get-MgApplicationOwnerByRef', 
               'Get-MgApplicationOwnerCount', 
               'Get-MgApplicationOwnerCountAsAppRoleAssignment', 
               'Get-MgApplicationOwnerCountAsEndpoint', 
               'Get-MgApplicationOwnerCountAsServicePrincipal', 
               'Get-MgApplicationOwnerCountAsUser', 
               'Get-MgApplicationSynchronization', 
               'Get-MgApplicationSynchronizationAccessToken', 
               'Get-MgApplicationSynchronizationJob', 
               'Get-MgApplicationSynchronizationJobBulkUpload', 
               'Get-MgApplicationSynchronizationJobBulkUploadContent', 
               'Get-MgApplicationSynchronizationJobCount', 
               'Get-MgApplicationSynchronizationJobSchema', 
               'Get-MgApplicationSynchronizationJobSchemaDirectory', 
               'Get-MgApplicationSynchronizationJobSchemaDirectoryCount', 
               'Get-MgApplicationSynchronizationSecretCount', 
               'Get-MgApplicationSynchronizationTemplate', 
               'Get-MgApplicationSynchronizationTemplateCount', 
               'Get-MgApplicationSynchronizationTemplateSchema', 
               'Get-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Get-MgApplicationSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgApplicationTemplate', 'Get-MgApplicationTemplateCount', 
               'Get-MgApplicationTokenIssuancePolicy', 
               'Get-MgApplicationTokenIssuancePolicyByRef', 
               'Get-MgApplicationTokenIssuancePolicyCount', 
               'Get-MgApplicationTokenLifetimePolicy', 
               'Get-MgApplicationTokenLifetimePolicyByRef', 
               'Get-MgApplicationTokenLifetimePolicyCount', 
               'Get-MgGroupAppRoleAssignment', 'Get-MgGroupAppRoleAssignmentCount', 
               'Get-MgServicePrincipal', 
               'Get-MgServicePrincipalAppManagementPolicy', 
               'Get-MgServicePrincipalAppManagementPolicyCount', 
               'Get-MgServicePrincipalAppRoleAssignedTo', 
               'Get-MgServicePrincipalAppRoleAssignedToCount', 
               'Get-MgServicePrincipalAppRoleAssignment', 
               'Get-MgServicePrincipalAppRoleAssignmentCount', 
               'Get-MgServicePrincipalByAppId', 'Get-MgServicePrincipalById', 
               'Get-MgServicePrincipalClaimMappingPolicy', 
               'Get-MgServicePrincipalClaimMappingPolicyByRef', 
               'Get-MgServicePrincipalClaimMappingPolicyCount', 
               'Get-MgServicePrincipalCount', 
               'Get-MgServicePrincipalCreatedObject', 
               'Get-MgServicePrincipalCreatedObjectAsServicePrincipal', 
               'Get-MgServicePrincipalCreatedObjectCount', 
               'Get-MgServicePrincipalCreatedObjectCountAsServicePrincipal', 
               'Get-MgServicePrincipalDelegatedPermissionClassification', 
               'Get-MgServicePrincipalDelegatedPermissionClassificationCount', 
               'Get-MgServicePrincipalDelta', 'Get-MgServicePrincipalEndpoint', 
               'Get-MgServicePrincipalEndpointCount', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicy', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Get-MgServicePrincipalHomeRealmDiscoveryPolicyCount', 
               'Get-MgServicePrincipalMemberGroup', 
               'Get-MgServicePrincipalMemberObject', 
               'Get-MgServicePrincipalMemberOf', 
               'Get-MgServicePrincipalMemberOfAsAdministrativeUnit', 
               'Get-MgServicePrincipalMemberOfAsDirectoryRole', 
               'Get-MgServicePrincipalMemberOfAsGroup', 
               'Get-MgServicePrincipalMemberOfCount', 
               'Get-MgServicePrincipalMemberOfCountAsAdministrativeUnit', 
               'Get-MgServicePrincipalMemberOfCountAsDirectoryRole', 
               'Get-MgServicePrincipalMemberOfCountAsGroup', 
               'Get-MgServicePrincipalOauth2PermissionGrant', 
               'Get-MgServicePrincipalOauth2PermissionGrantCount', 
               'Get-MgServicePrincipalOwnedObject', 
               'Get-MgServicePrincipalOwnedObjectAsApplication', 
               'Get-MgServicePrincipalOwnedObjectAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnedObjectAsEndpoint', 
               'Get-MgServicePrincipalOwnedObjectAsGroup', 
               'Get-MgServicePrincipalOwnedObjectAsServicePrincipal', 
               'Get-MgServicePrincipalOwnedObjectCount', 
               'Get-MgServicePrincipalOwnedObjectCountAsApplication', 
               'Get-MgServicePrincipalOwnedObjectCountAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnedObjectCountAsEndpoint', 
               'Get-MgServicePrincipalOwnedObjectCountAsGroup', 
               'Get-MgServicePrincipalOwnedObjectCountAsServicePrincipal', 
               'Get-MgServicePrincipalOwner', 
               'Get-MgServicePrincipalOwnerAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnerAsEndpoint', 
               'Get-MgServicePrincipalOwnerAsServicePrincipal', 
               'Get-MgServicePrincipalOwnerAsUser', 
               'Get-MgServicePrincipalOwnerByRef', 
               'Get-MgServicePrincipalOwnerCount', 
               'Get-MgServicePrincipalOwnerCountAsAppRoleAssignment', 
               'Get-MgServicePrincipalOwnerCountAsEndpoint', 
               'Get-MgServicePrincipalOwnerCountAsServicePrincipal', 
               'Get-MgServicePrincipalOwnerCountAsUser', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationApprovedClientApp', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationApprovedClientAppCount', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Get-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroupCount', 
               'Get-MgServicePrincipalSynchronization', 
               'Get-MgServicePrincipalSynchronizationAccessToken', 
               'Get-MgServicePrincipalSynchronizationJob', 
               'Get-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Get-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Get-MgServicePrincipalSynchronizationJobCount', 
               'Get-MgServicePrincipalSynchronizationJobSchema', 
               'Get-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Get-MgServicePrincipalSynchronizationJobSchemaDirectoryCount', 
               'Get-MgServicePrincipalSynchronizationSecretCount', 
               'Get-MgServicePrincipalSynchronizationTemplate', 
               'Get-MgServicePrincipalSynchronizationTemplateCount', 
               'Get-MgServicePrincipalSynchronizationTemplateSchema', 
               'Get-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Get-MgServicePrincipalSynchronizationTemplateSchemaDirectoryCount', 
               'Get-MgServicePrincipalTokenIssuancePolicy', 
               'Get-MgServicePrincipalTokenIssuancePolicyByRef', 
               'Get-MgServicePrincipalTokenIssuancePolicyCount', 
               'Get-MgServicePrincipalTokenLifetimePolicy', 
               'Get-MgServicePrincipalTokenLifetimePolicyByRef', 
               'Get-MgServicePrincipalTokenLifetimePolicyCount', 
               'Get-MgServicePrincipalTransitiveMemberOf', 
               'Get-MgServicePrincipalTransitiveMemberOfAsAdministrativeUnit', 
               'Get-MgServicePrincipalTransitiveMemberOfAsDirectoryRole', 
               'Get-MgServicePrincipalTransitiveMemberOfAsGroup', 
               'Get-MgServicePrincipalTransitiveMemberOfCount', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsAdministrativeUnit', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsDirectoryRole', 
               'Get-MgServicePrincipalTransitiveMemberOfCountAsGroup', 
               'Get-MgUserAppRoleAssignment', 'Get-MgUserAppRoleAssignmentCount', 
               'Invoke-MgFilterApplicationSynchronizationJobSchemaOperator', 
               'Invoke-MgFilterApplicationSynchronizationTemplateSchemaOperator', 
               'Invoke-MgFilterServicePrincipalSynchronizationJobSchemaOperator', 
               'Invoke-MgFilterServicePrincipalSynchronizationTemplateSchemaOperator', 
               'Invoke-MgFunctionApplicationSynchronizationJobSchema', 
               'Invoke-MgFunctionApplicationSynchronizationTemplateSchema', 
               'Invoke-MgFunctionServicePrincipalSynchronizationJobSchema', 
               'Invoke-MgFunctionServicePrincipalSynchronizationTemplateSchema', 
               'Invoke-MgInstantiateApplicationTemplate', 
               'Invoke-MgParseApplicationSynchronizationJobSchemaExpression', 
               'Invoke-MgParseApplicationSynchronizationTemplateSchemaExpression', 
               'Invoke-MgParseServicePrincipalSynchronizationJobSchemaExpression', 
               'Invoke-MgParseServicePrincipalSynchronizationTemplateSchemaExpression', 
               'New-MgApplication', 'New-MgApplicationAppManagementPolicyByRef', 
               'New-MgApplicationExtensionProperty', 
               'New-MgApplicationFederatedIdentityCredential', 
               'New-MgApplicationOwnerByRef', 
               'New-MgApplicationSynchronizationJob', 
               'New-MgApplicationSynchronizationJobOnDemand', 
               'New-MgApplicationSynchronizationJobSchemaDirectory', 
               'New-MgApplicationSynchronizationTemplate', 
               'New-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'New-MgApplicationTokenIssuancePolicyByRef', 
               'New-MgApplicationTokenLifetimePolicyByRef', 
               'New-MgGroupAppRoleAssignment', 'New-MgServicePrincipal', 
               'New-MgServicePrincipalAppRoleAssignedTo', 
               'New-MgServicePrincipalAppRoleAssignment', 
               'New-MgServicePrincipalClaimMappingPolicyByRef', 
               'New-MgServicePrincipalDelegatedPermissionClassification', 
               'New-MgServicePrincipalEndpoint', 
               'New-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'New-MgServicePrincipalOwnerByRef', 
               'New-MgServicePrincipalRemoteDesktopSecurityConfigurationApprovedClientApp', 
               'New-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'New-MgServicePrincipalSynchronizationJob', 
               'New-MgServicePrincipalSynchronizationJobOnDemand', 
               'New-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'New-MgServicePrincipalSynchronizationTemplate', 
               'New-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'New-MgServicePrincipalTokenIssuancePolicyByRef', 
               'New-MgServicePrincipalTokenLifetimePolicyByRef', 
               'New-MgUserAppRoleAssignment', 'Remove-MgApplication', 
               'Remove-MgApplicationAppManagementPolicyAppManagementPolicyByRef', 
               'Remove-MgApplicationByAppId', 'Remove-MgApplicationByUniqueName', 
               'Remove-MgApplicationExtensionProperty', 
               'Remove-MgApplicationFederatedIdentityCredential', 
               'Remove-MgApplicationFederatedIdentityCredentialByName', 
               'Remove-MgApplicationKey', 'Remove-MgApplicationLogo', 
               'Remove-MgApplicationOwnerDirectoryObjectByRef', 
               'Remove-MgApplicationPassword', 
               'Remove-MgApplicationSynchronization', 
               'Remove-MgApplicationSynchronizationJob', 
               'Remove-MgApplicationSynchronizationJobBulkUpload', 
               'Remove-MgApplicationSynchronizationJobBulkUploadContent', 
               'Remove-MgApplicationSynchronizationJobSchema', 
               'Remove-MgApplicationSynchronizationJobSchemaDirectory', 
               'Remove-MgApplicationSynchronizationTemplate', 
               'Remove-MgApplicationSynchronizationTemplateSchema', 
               'Remove-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Remove-MgApplicationTokenIssuancePolicyTokenIssuancePolicyByRef', 
               'Remove-MgApplicationTokenLifetimePolicyTokenLifetimePolicyByRef', 
               'Remove-MgGroupAppRoleAssignment', 'Remove-MgServicePrincipal', 
               'Remove-MgServicePrincipalAppRoleAssignedTo', 
               'Remove-MgServicePrincipalAppRoleAssignment', 
               'Remove-MgServicePrincipalByAppId', 
               'Remove-MgServicePrincipalClaimMappingPolicyClaimMappingPolicyByRef', 
               'Remove-MgServicePrincipalDelegatedPermissionClassification', 
               'Remove-MgServicePrincipalEndpoint', 
               'Remove-MgServicePrincipalHomeRealmDiscoveryPolicyHomeRealmDiscoveryPolicyByRef', 
               'Remove-MgServicePrincipalKey', 
               'Remove-MgServicePrincipalOwnerDirectoryObjectByRef', 
               'Remove-MgServicePrincipalPassword', 
               'Remove-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Remove-MgServicePrincipalRemoteDesktopSecurityConfigurationApprovedClientApp', 
               'Remove-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Remove-MgServicePrincipalSynchronization', 
               'Remove-MgServicePrincipalSynchronizationJob', 
               'Remove-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Remove-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Remove-MgServicePrincipalSynchronizationJobSchema', 
               'Remove-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Remove-MgServicePrincipalSynchronizationTemplate', 
               'Remove-MgServicePrincipalSynchronizationTemplateSchema', 
               'Remove-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Remove-MgServicePrincipalTokenIssuancePolicyByRef', 
               'Remove-MgServicePrincipalTokenIssuancePolicyTokenIssuancePolicyByRef', 
               'Remove-MgServicePrincipalTokenLifetimePolicyByRef', 
               'Remove-MgServicePrincipalTokenLifetimePolicyTokenLifetimePolicyByRef', 
               'Remove-MgUserAppRoleAssignment', 
               'Restart-MgApplicationSynchronizationJob', 
               'Restart-MgServicePrincipalSynchronizationJob', 
               'Set-MgApplicationLogo', 'Set-MgApplicationSynchronization', 
               'Set-MgApplicationSynchronizationJobBulkUploadContent', 
               'Set-MgApplicationSynchronizationSecret', 
               'Set-MgApplicationVerifiedPublisher', 
               'Set-MgServicePrincipalSynchronization', 
               'Set-MgServicePrincipalSynchronizationJobBulkUploadContent', 
               'Set-MgServicePrincipalSynchronizationSecret', 
               'Start-MgApplicationSynchronizationJob', 
               'Start-MgServicePrincipalSynchronizationJob', 
               'Suspend-MgApplicationSynchronizationJob', 
               'Suspend-MgServicePrincipalSynchronizationJob', 
               'Test-MgApplicationProperty', 
               'Test-MgApplicationSynchronizationJobCredential', 
               'Test-MgServicePrincipalProperty', 
               'Test-MgServicePrincipalSynchronizationJobCredential', 
               'Update-MgApplication', 'Update-MgApplicationByAppId', 
               'Update-MgApplicationByUniqueName', 
               'Update-MgApplicationExtensionProperty', 
               'Update-MgApplicationFederatedIdentityCredential', 
               'Update-MgApplicationFederatedIdentityCredentialByName', 
               'Update-MgApplicationSynchronizationJob', 
               'Update-MgApplicationSynchronizationJobBulkUpload', 
               'Update-MgApplicationSynchronizationJobSchema', 
               'Update-MgApplicationSynchronizationJobSchemaDirectory', 
               'Update-MgApplicationSynchronizationTemplate', 
               'Update-MgApplicationSynchronizationTemplateSchema', 
               'Update-MgApplicationSynchronizationTemplateSchemaDirectory', 
               'Update-MgGroupAppRoleAssignment', 'Update-MgServicePrincipal', 
               'Update-MgServicePrincipalAppRoleAssignedTo', 
               'Update-MgServicePrincipalAppRoleAssignment', 
               'Update-MgServicePrincipalByAppId', 
               'Update-MgServicePrincipalDelegatedPermissionClassification', 
               'Update-MgServicePrincipalEndpoint', 
               'Update-MgServicePrincipalRemoteDesktopSecurityConfiguration', 
               'Update-MgServicePrincipalRemoteDesktopSecurityConfigurationApprovedClientApp', 
               'Update-MgServicePrincipalRemoteDesktopSecurityConfigurationTargetDeviceGroup', 
               'Update-MgServicePrincipalSynchronizationJob', 
               'Update-MgServicePrincipalSynchronizationJobBulkUpload', 
               'Update-MgServicePrincipalSynchronizationJobSchema', 
               'Update-MgServicePrincipalSynchronizationJobSchemaDirectory', 
               'Update-MgServicePrincipalSynchronizationTemplate', 
               'Update-MgServicePrincipalSynchronizationTemplateSchema', 
               'Update-MgServicePrincipalSynchronizationTemplateSchemaDirectory', 
               'Update-MgUserAppRoleAssignment'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Remove-MgApplicationAppManagementPolicyByRef', 
               'Remove-MgApplicationOwnerByRef', 
               'Remove-MgApplicationTokenIssuancePolicyByRef', 
               'Remove-MgApplicationTokenLifetimePolicyByRef', 
               'Remove-MgServicePrincipalClaimMappingPolicyByRef', 
               'Remove-MgServicePrincipalHomeRealmDiscoveryPolicyByRef', 
               'Remove-MgServicePrincipalOwnerByRef'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInRgYJKoZIhvcNAQcCoIInNzCCJzMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAIKtLGci9PE7Mn
# PthJdSGGDAdHFpTY6x2AUbCnpWIDgqCCDLowggX1MIID3aADAgECAhMzAAACHU0Z
# yE7XD1dIAAAAAAIdMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
# b2RlIFNpZ25pbmcgUENBIDIwMjQwHhcNMjYwNDE2MTg1OTQzWhcNMjcwNDE1MTg1
# OTQzWjB0MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYD
# VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQDQvewXxx9gZZFC6Ys1WBay8BJ8kGA4JQnH5CMafqOASlTpK9H8
# o5ZXTXt0caVQTNMUPt445wXYD+dFtaKWTwDn1I52oUSrC9vJin1Gsqt+zyKJL5Dg
# 3eQXbQNR61DmMy20GLTIO3SFed9Rfi/ophgCLGFLDR3r0KvHjwMb/jYWS0celV/4
# Lz27LfAekm8v9E5IXaeiXbAUYZKK090n4CVl3JBtbN+9DtI9SNu/yjvozW52/u7R
# X/Ttpa/KDlpuokZ+Zcbvmtd9ur9gFLvZzh41o9MsE/clQtdaFWGvuo6Jua/ntpgk
# ey3E5/vBFe+MJPG6phdnuo6r57ZudCudiI1bAgMBAAGjggGbMIIBlzAOBgNVHQ8B
# Af8EBAMCB4AwHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0O
# BBYEFH6QuMwqcPG0hQlQ6c5jCtTTLrVeMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQL
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAxMis1MDc1NTkw
# HwYDVR0jBBgwFoAUf1k/VCHarU/vBeXmo9ctBpQSCDEwYAYDVR0fBFkwVzBVoFOg
# UYZPaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0
# JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNybDBtBggrBgEFBQcBAQRh
# MF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y2VydHMvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNy
# dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQBKTbYOjzwTG/DXGaz9
# s6+fQeaTtDcFmMY+5UyVFCyj7Pv+5i37qfX8lSL/tBIfYQfWsMuBQlfZurJD6r4H
# VJ2CeH+1fgiq8dcHdVKoZ3Sa2qXoX3cq9iS8cVb06B7+5/XJ7I0OxHH9fDsvJ3T3
# w5V/ZtAIFmLrl+P0CtG+92uzRsn0nTbdFjOkLMLWPLAU3THohKRlSEMgFJpPkm5n
# 5UAZ35xX6FWCrDLsSKb555bTifwa8mJBwdlof0bmfYidH+dxZ1FdDxvLnNl9zeKs
# A4kejaaIqqIPguhwAti5Ql7BlTNoJNwxCvBmqW2MQLnCkYN/VVUsR3V2x/rcTNzo
# Bf/Z/SpROvdaA2ZOOd1uioXJt3tdLQ7vHpqpib0KfWr/FWXW10q38VxfCnRQBqzb
# SuztR7nEMuzX7Ck+B/XaPDXd1qh72+QYyB0Z2VzWmO9zsnb9Uq/dwu8LGeQqnyu6
# 7SDGACvnXii2fb9+US492VTnXSnFKyqwgzUyFMtZK1/sHYTv6bG4TtQUygQxTN+Z
# V+aJIlKO2MqZ7bKrAnOzS9m6NgoTdWOq11bTOZwKlIEV/EhV9SWkDmdpR/hPPT2v
# 6TEj4F8PT/zHjRezIU5c/DGlt/VhY/pK0XkJtEyMmmS1BMtjU/rqBZVMIm3dnxQs
# /TBByr+Cf8Z1r7aifQVQ+WSqzjCCBr0wggSloAMCAQICEzMAAAA5O7Y3Gb8GHWcA
# AAAAADkwDQYJKoZIhvcNAQEMBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDExMB4XDTI0MDgwODIwNTQxOFoXDTM2MDMyMjIyMTMwNFow
# VzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEo
# MCYGA1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAyNDCCAiIwDQYJ
# KoZIhvcNAQEBBQADggIPADCCAgoCggIBANgBnB7jOMeqlRYHNa265v4IY9fH8TKh
# emHfPINe1gpLaV3dhg324WwH06LcHbpnsBukCDNitryo0dtS/EW6I/yEL/bLSY8h
# KpbfQuWusBPr9qazYcDxCW/qnjb5JsI1s8bNOg3bVATvQVL4tcf03aTycsz8QeCd
# M0l/yHRObJ9QqazM1r6VPEOJ7LL+uEEb73w6QCuhs89a1uv1zerOYMnsneRRwCbp
# yW11IcggU0cRKDDq1pjVJzIbIF6+oiXXbReOsgeI8zu1FyQfK0fVkaya8SmVHQ/t
# Of23mZ4W9k0Ri22QW9p3UgSC5OUDktKxxcCmGL6tXLfOGSWHIIV4YrTJTT6PNty5
# REojHJuZHArkF9VnHTERWoTjAzfI3kP+5b4alUdhgAZ7ttOu1bVnXfHaqPYl2rPs
# 20ji03LOVWsh/radgE17es5hL+t6lV0eVHrVhsssROWJuz2MXMCt7iw7lFPG9LXK
# Gjsmonn2gotGdHIuEg5JnJMJVmixd5LRlkmgYRZKzhxSCwyoGIq0PhaA7Y+VPct5
# pCHkijcIIDm0nlkK+0KyepolcqGm0T/GYQRMhHJlGOOmVQop36wUVUYklUy++vDW
# eEgEo4s7hxN6mIbf2MSIQ/iIfMZgJxC69oukMUXCrOC3SkE/xIkgpfl22MM1itkZ
# 35nNXkMolU1lAgMBAAGjggFOMIIBSjAOBgNVHQ8BAf8EBAMCAYYwEAYJKwYBBAGC
# NxUBBAMCAQAwHQYDVR0OBBYEFH9ZP1Qh2q1P7wXl5qPXLQaUEggxMBkGCSsGAQQB
# gjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNydDANBgkqhkiG9w0BAQwFAAOCAgEAFJQfOChP7onn6fLI
# MKrSlN1WYKwDFgAddymOUO3FrM8d7B/W/iQ6DxXsDn7D5W4wMwYeLystcEqfkjz4
# NURRgazyMu5yRzQh4LqjA4tStTcJh1opExo7nn5PuPBYnbu0+THSuVHTe0VTTPVh
# ily/piFrDo3axQ9P4C+Ol5yet+2gTfekICS5xS+cYfSIvgn0JksVBVMYVI5QFu/q
# hnLhsEFEUzG8fvv0hjgkO+lkpV9ty6GkN4vdnd7ya6Q6aR9y34aiM1qmxaxBi6OU
# nyNl6fkuun/diTFnYDLTppOkr/mg5WSfCiDVMNCxtj4wPKC5OmHm1DQIt/MNokbb
# H3UGsFP1QbzsLocuSqLCvH09Io3fDPTmscR9Y75G4qX7RTX8AdBPo0I6OEojf39z
# uFZt0qOHm65YWQE69cZM2ueE1MB05dNNgHK9gTE7zKvK/fg8B2qjW88MT/WF5V5u
# vZGtqa9FSL2RazArA+rDPuf6JGYz4HpgMZHB4S6szWSKYBv0VisCzfxgeU+dquXW
# 9bd0auYlOB58DPcOYKdc3Se94g+xL4pcEhbB54JOgAkwYTu/9dLeH2pDqeJZAABV
# DWRQCaXfO5LgyKwKCLYXpigrZYCjUSBcr+Ve8PFWMhVTQl0v4q8J/AUmQN5W4n10
# 1cY2L4A7GTQG1h32HHAvfQESWP0xghniMIIZ3gIBATBuMFcxCzAJBgNVBAYTAlVT
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
# c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMjQCEzMAAAIdTRnITtcPV0gAAAAAAh0w
# DQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
# KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIAePaXaw
# aer4vCDZ7ISsZ3pIQYWDqlie93g6QxNe3ZcNMEIGCisGAQQBgjcCAQwxNDAyoBSA
# EgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20w
# DQYJKoZIhvcNAQEBBQAEggEAiCET3YvnJt7hAXpp8N14Jbb/ZRkvo93TS0Faqo4H
# FB0SPXvO3EcB1KR0Px4FH4gC9foNlhhe0Ub+QFKgEnxZ41rfkNFzKENP69V2AEle
# WVGmQ0i+8lTsv9u8yzYrrrllvXh7eUrN+1OcJdi/NwAP8h3vRo7wyTYU9CspoNzA
# A16xdq+7kwd9cmqEo8VPqyTsJfoMJHTi4wDxuztxdx+ao9SvW1CBjc92HUKYXpfn
# yCYcB5OgZ0aGbABdpfTLEboGinPlmvHsA5XuuZiZj9JFRduruwG6NjfdecZP/LwO
# GMWYcunQJ7lyJ3cNw75FRnuLRmORDeco+4QrFYV4CxGknKGCF5QwgheQBgorBgEE
# AYI3AwMBMYIXgDCCF3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUD
# BAIBBQAwggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoD
# ATAxMA0GCWCGSAFlAwQCAQUABCDVf9jLCfVe0D3nlf9WW/sLuRAcMF1Bbpy31oYe
# 5aqx3QIGajFNPOnbGBMyMDI2MDcxMTAwNDIzOC44NDNaMASAAgH0oIHRpIHOMIHL
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxN
# aWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRT
# UyBFU046QTkzNS0wM0UwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFNlcnZpY2WgghHqMIIHIDCCBQigAwIBAgITMwAAAifVwIPDsS5XLQABAAAC
# JzANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAe
# Fw0yNjAyMTkxOTQwMDRaFw0yNzA1MTcxOTQwMDRaMIHLMQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmlj
# YSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046QTkzNS0wM0Uw
# LUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDixWy1fDOSL4qj3A1pady+elID
# LwnF3UuLzJIOWwGHcEgrxxwtnyviUIDmmxylTUl1u+2rBPp2zT4BwwQhvGaJpExq
# vPLlDFlbfmSflKI86eFqofiZ7j8NTRO4l7wGg9Njm+muNauTcFW2qdfIjKE950Ok
# rm9MnMOGYy+fibNYdxTPRPq1T4MLZK3s3vdMyMEOldcOQkSKpxD6/1Gk6gOmCu2K
# gI8f0ex6vYxnKDl9W0OLSEa/6y82oIbsm+1QBifOQ47xWKTG1CmvtGr85LzA75/M
# AcUmRw5/of/qET0UFV1WulMcJrI6DASAsNCNB+6WLrotuBZAj+VMlqbn5RMZ6Q4I
# Y7JwaAiIXh7VjxrnwUOYZG8WEGhfrA98di+7LEn9AqvvEOyG+UQcjVhCCbMGXigJ
# XSApeyeWupCsD0jgQMNCxfB5BLBDWxgdY3dJBEPgxfkgTDQLBggtVv2d5CYxHKgI
# ItB4bI5eSb5jkIG2WotnFetT0legpw/Eozwf39ao6tENY21eVWIzRw/GsmvwjYQF
# 6vVrxOD0pGVsfqGF8s3VPeY7hI2TxHFMqNA0IB/a2NLY7JTxYAKAP/11EJZt7xbq
# DLMgD1YDdGEzGpQijm3nAPCL2CebP/jmu90abJ2W425yglGHTI/nCBrwSpfRCgwz
# rfFelJaCKM6+35aFfwIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFNLW58N4MGSG6ud7
# jWqgT92orfReMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1Ud
# HwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggr
# BgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
# bS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIw
# MTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgw
# DgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQAqncud4PSC1teb2H6n
# Ruy7sDiKK13FXJirVB4Tfwjdo2Mb+QL4j7wZ/k4G9P0CANHZFrDQcK0VFDTysrYu
# 8Z0Aha14acDZPsyIoPvAGRRhaHEuf7NckRjkfa/ylo1KyII8jbL9N9sJAqBPL8V4
# FNBjljv+1GHDOw127rZz5ZSTPoAPb2SA0v5yDgcpUMfxglPyp6cnPPoQpTtD9OGx
# 8Dwm2P+o1TPxBIy6I0T9RauulogVCvKwflfeLTcKAvnSG1rCjerSXmU1DNXOsAD/
# bsrSjgbX5mAbD7XTRMF/vawAWESFcn/BjjizxeWZb00aYSlkJA2rVtFlMM481aVW
# XdAbXPP5RzUiWTlgyHf/G7lCxHYWGIZuB13T3aI6Y8mEgn/ou40aiFJo8r0+i0P5
# GdNneWtxiR0CMKUfko+5s/73cwe1Wfp8BKXa270cicVQasFf5sRV7pFm+V7fNRXw
# Cu7anTOmga76zO7/2t+zOlibvphT+Q6Zd+B2qYsSn4xBaY+YzHpnycLW5cvJyhPx
# BCcb1oRYfhRzCADb2utI2EtGCjc2P2ii4LyR4QMb/n8cOweL9IqVTKKzzVk+zZJx
# V3vrp4LyuQXw0O30la6BcHdNAAAB9UC83zs3G9d+AlIfZLM97tMUNKWjbBpIirFx
# 6LTDFXVtZQd7hqzLYByjbjH0ujCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkA
# AAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVow
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX
# 9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1q
# UoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8d
# q6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byN
# pOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2k
# rnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4d
# Pf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgS
# Uei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8
# QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6Cm
# gyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzF
# ER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQID
# AQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU
# KqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1
# GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0
# bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMA
# QTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbL
# j+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
# Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIz
# LmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwU
# tj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN
# 3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU
# 5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5
# KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGy
# qVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB6
# 2FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltE
# AY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFp
# AUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcd
# FYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRb
# atGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQd
# VTNYs6FwZvKhggNNMIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2Eg
# T3BlcmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOkE5MzUtMDNFMC1E
# OTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEw
# BwYFKw4DAhoDFQAjHzqthPwO0GDckDMA6x54lIiMKqCBgzCBgKR+MHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7ftsPzAiGA8y
# MDI2MDcxMDEzMDM1OVoYDzIwMjYwNzExMTMwMzU5WjB0MDoGCisGAQQBhFkKBAEx
# LDAqMAoCBQDt+2w/AgEAMAcCAQACAgoiMAcCAQACAhKXMAoCBQDt/L2/AgEAMDYG
# CisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEA
# AgMBhqAwDQYJKoZIhvcNAQELBQADggEBAHfFBWuOXO9jgOYAHEuBgOHlMrGdlYNe
# VVG/+dWxieO+XyLEhEU5sh9t9qm/eyOMyQMMIjC3d3tE3u9kZr39/QFY4I1X84tu
# 4IntAUyJYYo0omujS4llKafyey0I0Bx9AR6OuiVLs4h9OAeYJF0DOKXl3CETa6ES
# /QfKLiLSL+4hzj2PvTT6E6rd8Ckk8ZbVtGLquR7ixXVpP23BpnKMrKy4K1N/Cwer
# 4eXku8ogXrtLO7jCg9mLqFa8Hg8GBJ6EMH6/rTPUqEvA7MDkHN7xK1MA/UEl0hRM
# T+5U1ofwFrBW1+OZD48CB29I+CUoDXr2lIVRiCjtvZ257lxYDA3W2JcxggQNMIIE
# CQIBATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
# JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAifVwIPD
# sS5XLQABAAACJzANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqG
# SIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCDEHjj7nwtN76Ga7vimzo5xE+Lulw6P
# hgWvE3wAZPmj5DCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIOXnARo1oVIc
# OLJKDqlE0adq/jZ9TXdlnXWRcXGThBFyMIGYMIGApH4wfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAIn1cCDw7EuVy0AAQAAAicwIgQgQoWdq0b3itgU
# hKFs1iD+RKVuVpxwbIxnl7sKvU/QizQwDQYJKoZIhvcNAQELBQAEggIApXa5T1W/
# YuWBvIxNSVvZRy2s0+CvfoKDi7NfNoFqTCGFI9etq+r4lIfisBw598nK8BRoKIaN
# JbmkVjaE5E7TJtV4NHSoBvsXIlizz3x0pFuQRu5OGyA8gv5lnWmFVgl5MVexGp7i
# EK76Ki+HrwHw66nOhDrZb3xGgvdqlg2irJZWYT1krsapUgYXgzDZs3Dwh5cm+mnM
# NBFZbhcTEpZNXy6UxlwSGHW9Ir5uKXHkY573L8oJV52R2n39kDL75Tr2I5k5bC/G
# Y3KZJ8FYYamElxk94OTxupDUA2hGNdrr03n+fWQWLqDH0l269pDT/0Z+Vs+s/Am5
# iz4KnUTRuDIFOx/hWu6m7mH9vtV68Aw4/yzJpytqviwgR3OUhh0J5KzAtE98B9ox
# CGgj3uTSxaOq2OkUjtsUhdvWti8+OMC69g2T6zM49PqGcrZGS4tkTTZbPcnLsZck
# /Xk/QBdqmSWn0GHRzjtuGOcIiergtkObPdFudEamyjGW8BEwFaUV1WHmhlJl5OhQ
# wyxlyEBXaAgIBT0/tSSBcpE8LlRvmE87cVqxoS/Mia59Gr+usD+9jaxJu3J6N6TN
# /06bonGMv7fHQzHUQm0aNP2+WMa7B8MToiXVwxKyZxGG1R39QC6Do3G7+HibUhlv
# Cczzf0CKA9JIBiG6Er24NJ7TgBTGo9yqe6g=
# SIG # End signature block
