#
# Module manifest for module 'Microsoft.Graph.BackupRestore'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/10/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.BackupRestore.psm1'

# Version number of this module.
ModuleVersion = '2.38.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'a891fdeb-65dd-4a27-b9e2-a4b617ad6d2e'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.38.1'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.BackupRestore.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.BackupRestore.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Enable-MgSolutionBackupRestore', 'Get-MgSolutionBackupRestore', 
               'Get-MgSolutionBackupRestoreBrowseSession', 
               'Get-MgSolutionBackupRestoreBrowseSessionCount', 
               'Get-MgSolutionBackupRestoreDriveInclusionRule', 
               'Get-MgSolutionBackupRestoreDriveInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreDriveProtectionUnit', 
               'Get-MgSolutionBackupRestoreDriveProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreDriveProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreDriveProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicy', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyCount', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxInclusionRule', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxProtectionUnit', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreExchangeProtectionPolicyMailboxProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSession', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionCount', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifact', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifactCount', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifactRestorePoint', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifact', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactBulkAdditionRequest', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactBulkAdditionRequestCount', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactCount', 
               'Get-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactRestorePoint', 
               'Get-MgSolutionBackupRestoreMailboxInclusionRule', 
               'Get-MgSolutionBackupRestoreMailboxInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreMailboxProtectionUnit', 
               'Get-MgSolutionBackupRestoreMailboxProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreMailboxProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreMailboxProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessBrowseSession', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessBrowseSessionCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicy', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveInclusionRule', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveProtectionUnit', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicyDriveProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSession', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifact', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactBulkAdditionRequest', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactBulkAdditionRequestCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactCount', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactRestorePoint', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionGranularDriveRestoreArtifact', 
               'Get-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionGranularDriveRestoreArtifactCount', 
               'Get-MgSolutionBackupRestorePoint', 
               'Get-MgSolutionBackupRestorePointCount', 
               'Get-MgSolutionBackupRestorePointProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionPolicy', 
               'Get-MgSolutionBackupRestoreProtectionPolicyCount', 
               'Get-MgSolutionBackupRestoreProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitAsDriveProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitAsMailboxProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitAsSiteProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreProtectionUnitCountAsDriveProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitCountAsMailboxProtectionUnit', 
               'Get-MgSolutionBackupRestoreProtectionUnitCountAsSiteProtectionUnit', 
               'Get-MgSolutionBackupRestoreServiceApp', 
               'Get-MgSolutionBackupRestoreServiceAppCount', 
               'Get-MgSolutionBackupRestoreSession', 
               'Get-MgSolutionBackupRestoreSessionCount', 
               'Get-MgSolutionBackupRestoreSharePointBrowseSession', 
               'Get-MgSolutionBackupRestoreSharePointBrowseSessionCount', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicy', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicyCount', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteInclusionRule', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteProtectionUnit', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreSharePointProtectionPolicySiteProtectionUnitCount', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSession', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionCount', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionGranularSiteRestoreArtifact', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionGranularSiteRestoreArtifactCount', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifact', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactBulkAdditionRequest', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactBulkAdditionRequestCount', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactCount', 
               'Get-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactRestorePoint', 
               'Get-MgSolutionBackupRestoreSiteInclusionRule', 
               'Get-MgSolutionBackupRestoreSiteInclusionRuleCount', 
               'Get-MgSolutionBackupRestoreSiteProtectionUnit', 
               'Get-MgSolutionBackupRestoreSiteProtectionUnitBulkAdditionJob', 
               'Get-MgSolutionBackupRestoreSiteProtectionUnitBulkAdditionJobCount', 
               'Get-MgSolutionBackupRestoreSiteProtectionUnitCount', 
               'Initialize-MgSolutionBackupRestoreProtectionPolicy', 
               'Initialize-MgSolutionBackupRestoreServiceApp', 
               'Initialize-MgSolutionBackupRestoreSession', 
               'Invoke-MgBrowseSolutionBackupRestoreBrowseSession', 
               'Invoke-MgDeactivateSolutionBackupRestoreProtectionPolicy', 
               'Invoke-MgDeactivateSolutionBackupRestoreServiceApp', 
               'Invoke-MgOffboardSolutionBackupRestoreProtectionUnit', 
               'New-MgSolutionBackupRestoreBrowseSession', 
               'New-MgSolutionBackupRestoreDriveInclusionRule', 
               'New-MgSolutionBackupRestoreDriveProtectionUnit', 
               'New-MgSolutionBackupRestoreDriveProtectionUnitBulkAdditionJob', 
               'New-MgSolutionBackupRestoreExchangeProtectionPolicy', 
               'New-MgSolutionBackupRestoreExchangeRestoreSession', 
               'New-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifact', 
               'New-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifact', 
               'New-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactBulkAdditionRequest', 
               'New-MgSolutionBackupRestoreMailboxInclusionRule', 
               'New-MgSolutionBackupRestoreMailboxProtectionUnit', 
               'New-MgSolutionBackupRestoreMailboxProtectionUnitBulkAdditionJob', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessBrowseSession', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicy', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessRestoreSession', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifact', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactBulkAdditionRequest', 
               'New-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionGranularDriveRestoreArtifact', 
               'New-MgSolutionBackupRestorePoint', 
               'New-MgSolutionBackupRestoreProtectionPolicy', 
               'New-MgSolutionBackupRestoreServiceApp', 
               'New-MgSolutionBackupRestoreSession', 
               'New-MgSolutionBackupRestoreSharePointBrowseSession', 
               'New-MgSolutionBackupRestoreSharePointProtectionPolicy', 
               'New-MgSolutionBackupRestoreSharePointRestoreSession', 
               'New-MgSolutionBackupRestoreSharePointRestoreSessionGranularSiteRestoreArtifact', 
               'New-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifact', 
               'New-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactBulkAdditionRequest', 
               'New-MgSolutionBackupRestoreSiteInclusionRule', 
               'New-MgSolutionBackupRestoreSiteProtectionUnit', 
               'New-MgSolutionBackupRestoreSiteProtectionUnitBulkAdditionJob', 
               'Remove-MgSolutionBackupRestore', 
               'Remove-MgSolutionBackupRestoreBrowseSession', 
               'Remove-MgSolutionBackupRestoreDriveInclusionRule', 
               'Remove-MgSolutionBackupRestoreDriveProtectionUnit', 
               'Remove-MgSolutionBackupRestoreDriveProtectionUnitBulkAdditionJob', 
               'Remove-MgSolutionBackupRestoreExchangeProtectionPolicy', 
               'Remove-MgSolutionBackupRestoreExchangeRestoreSession', 
               'Remove-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifact', 
               'Remove-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifact', 
               'Remove-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactBulkAdditionRequest', 
               'Remove-MgSolutionBackupRestoreMailboxInclusionRule', 
               'Remove-MgSolutionBackupRestoreMailboxProtectionUnit', 
               'Remove-MgSolutionBackupRestoreMailboxProtectionUnitBulkAdditionJob', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessBrowseSession', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicy', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessRestoreSession', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifact', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactBulkAdditionRequest', 
               'Remove-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionGranularDriveRestoreArtifact', 
               'Remove-MgSolutionBackupRestorePoint', 
               'Remove-MgSolutionBackupRestoreProtectionPolicy', 
               'Remove-MgSolutionBackupRestoreServiceApp', 
               'Remove-MgSolutionBackupRestoreSession', 
               'Remove-MgSolutionBackupRestoreSharePointBrowseSession', 
               'Remove-MgSolutionBackupRestoreSharePointProtectionPolicy', 
               'Remove-MgSolutionBackupRestoreSharePointRestoreSession', 
               'Remove-MgSolutionBackupRestoreSharePointRestoreSessionGranularSiteRestoreArtifact', 
               'Remove-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifact', 
               'Remove-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactBulkAdditionRequest', 
               'Remove-MgSolutionBackupRestoreSiteInclusionRule', 
               'Remove-MgSolutionBackupRestoreSiteProtectionUnit', 
               'Remove-MgSolutionBackupRestoreSiteProtectionUnitBulkAdditionJob', 
               'Search-MgSolutionBackupRestorePoint', 
               'Stop-MgSolutionBackupRestoreProtectionUnitOffboard', 
               'Update-MgSolutionBackupRestore', 
               'Update-MgSolutionBackupRestoreBrowseSession', 
               'Update-MgSolutionBackupRestoreDriveInclusionRule', 
               'Update-MgSolutionBackupRestoreDriveProtectionUnit', 
               'Update-MgSolutionBackupRestoreDriveProtectionUnitBulkAdditionJob', 
               'Update-MgSolutionBackupRestoreExchangeProtectionPolicy', 
               'Update-MgSolutionBackupRestoreExchangeRestoreSession', 
               'Update-MgSolutionBackupRestoreExchangeRestoreSessionGranularMailboxRestoreArtifact', 
               'Update-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifact', 
               'Update-MgSolutionBackupRestoreExchangeRestoreSessionMailboxRestoreArtifactBulkAdditionRequest', 
               'Update-MgSolutionBackupRestoreMailboxInclusionRule', 
               'Update-MgSolutionBackupRestoreMailboxProtectionUnit', 
               'Update-MgSolutionBackupRestoreMailboxProtectionUnitBulkAdditionJob', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessBrowseSession', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessProtectionPolicy', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessRestoreSession', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifact', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionDriveRestoreArtifactBulkAdditionRequest', 
               'Update-MgSolutionBackupRestoreOneDriveForBusinessRestoreSessionGranularDriveRestoreArtifact', 
               'Update-MgSolutionBackupRestorePoint', 
               'Update-MgSolutionBackupRestoreProtectionPolicy', 
               'Update-MgSolutionBackupRestoreServiceApp', 
               'Update-MgSolutionBackupRestoreSession', 
               'Update-MgSolutionBackupRestoreSharePointBrowseSession', 
               'Update-MgSolutionBackupRestoreSharePointProtectionPolicy', 
               'Update-MgSolutionBackupRestoreSharePointRestoreSession', 
               'Update-MgSolutionBackupRestoreSharePointRestoreSessionGranularSiteRestoreArtifact', 
               'Update-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifact', 
               'Update-MgSolutionBackupRestoreSharePointRestoreSessionSiteRestoreArtifactBulkAdditionRequest', 
               'Update-MgSolutionBackupRestoreSiteInclusionRule', 
               'Update-MgSolutionBackupRestoreSiteProtectionUnit', 
               'Update-MgSolutionBackupRestoreSiteProtectionUnitBulkAdditionJob'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Enable-MgBackupRestore', 
               'Initialize-MgBackupRestoreProtectionPolicy', 
               'Initialize-MgBackupRestoreServiceApp', 
               'Initialize-MgBackupRestoreSession', 'Search-MgBackupRestorePoint'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInbgYJKoZIhvcNAQcCoIInXzCCJ1sCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCAHMLZZbdURdEMF
# 59YCd8zqLaFbeshNJam1SVEpYXNWMqCCDMkwggYEMIID7KADAgECAhMzAAACHPrN
# xZvoL37EAAAAAAIcMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
# b2RlIFNpZ25pbmcgUENBIDIwMjQwHhcNMjYwNDE2MTg1OTQxWhcNMjcwNDE1MTg1
# OTQxWjB0MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYD
# VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQDVsZfgOKmM31HPfoWOoNEiw0SlCiIxUMC0I9NMWbucKOw/e9lP
# oAoehQVu6SG65V4EPzrYsnBnFPNoi4/HoOdjhz1qkrEt4I6tEcxXU6oOeY9zGveC
# /3iBeuhLYxM3M/PkcUoebF+Nednm8OkdSPoDu8imViHPQq/8CQUu0WRR4rE+dMRf
# rpVqfmNi2qWCX94T4MsepijGVkwE//tJg0ryAiYdHT34LSnlG/RSBZmQRGWZ5g8j
# qnKjRParSqMft1gvjuUTVgtWNZfgcLFSK5Wa0myrq8OPcgTGGsRgun+tnSS+IxDT
# xVsAPH1OzvPjwomguByhUe/OcvUN0D5Wmp7xAgMBAAGjggGqMIIBpjAOBgNVHQ8B
# Af8EBAMCB4AwHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0O
# BBYEFNoH7a2YDjOSwpkp6DHcmUS7J+0yMFQGA1UdEQRNMEukSTBHMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxFjAUBgNVBAUT
# DTIzMDAxMis1MDc1NjkwHwYDVR0jBBgwFoAUf1k/VCHarU/vBeXmo9ctBpQSCDEw
# YAYDVR0fBFkwVzBVoFOgUYZPaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
# cy9jcmwvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNy
# bDBtBggrBgEFBQcBAQRhMF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cubWljcm9z
# b2Z0LmNvbS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmcl
# MjBQQ0ElMjAyMDI0LmNydDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4IC
# AQAUnEqhaRXe0T3hIJjvdQErEkrA/7bByjn6t5IArODkkRjzkYwtKMc2yYj2quaN
# rLutWw2YZcngKPy1b71YyDJQTy4NDRwaSh9Tw5thrk3NmcPrAHia5vtcBJ1CgtKK
# 7mQbIcQ22d/N3813ayCDDFewu1+jsZmX+r/aTEqaOM4TVxVtRSkuCy8nAXKuChOK
# Li/zA4XuH8iEYqIsj2YoNaeSxVmeGiERXpKdo3dDmYi0kO5w2D8VS4c3+9h6gElY
# BaAAg/dYErBg27qT3vv0zRDJhJufvCNylA8S7/+8H5E/PV5cng6na9VV/w9OV3qu
# uND6zdGa2EX38Glp50F9AIQk3p2xXmcvorDeM4XJ7UlWYBi6g80J1SSOQnInCYFE
# msfUNn3+1AaTJKSJL83quKArTac2pKhu0Yzzzrzo6HrsRiQKzpnRBb1/dMa6P3hz
# 75XbMRBctNsFhZC07WCmjExdLg2eHW5uV0TY8D5+6wozJf7vF3+WHkYPO85Z+BC6
# U4FkNbYNycZ9cE4j1tXRdyDCfml6c0HWPHjNVDObrv9lKt3qUqFpX38VCqVCyNOO
# 1UcXfQiVjJw32U2WUKZjt/neJKHEBsm9kFsLuWzkQ53+qcaSaytmsCnk2gOglrlD
# 5d3kKyvvAw+rzm0lT8K38P6PLxfZQHhu4W8dV7Av8N2ZmDCCBr0wggSloAMCAQIC
# EzMAAAA5O7Y3Gb8GHWcAAAAAADkwDQYJKoZIhvcNAQEMBQAwgYgxCzAJBgNVBAYT
# AlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBS
# b290IENlcnRpZmljYXRlIEF1dGhvcml0eSAyMDExMB4XDTI0MDgwODIwNTQxOFoX
# DTM2MDMyMjIyMTMwNFowVzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEoMCYGA1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQ
# Q0EgMjAyNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANgBnB7jOMeq
# lRYHNa265v4IY9fH8TKhemHfPINe1gpLaV3dhg324WwH06LcHbpnsBukCDNitryo
# 0dtS/EW6I/yEL/bLSY8hKpbfQuWusBPr9qazYcDxCW/qnjb5JsI1s8bNOg3bVATv
# QVL4tcf03aTycsz8QeCdM0l/yHRObJ9QqazM1r6VPEOJ7LL+uEEb73w6QCuhs89a
# 1uv1zerOYMnsneRRwCbpyW11IcggU0cRKDDq1pjVJzIbIF6+oiXXbReOsgeI8zu1
# FyQfK0fVkaya8SmVHQ/tOf23mZ4W9k0Ri22QW9p3UgSC5OUDktKxxcCmGL6tXLfO
# GSWHIIV4YrTJTT6PNty5REojHJuZHArkF9VnHTERWoTjAzfI3kP+5b4alUdhgAZ7
# ttOu1bVnXfHaqPYl2rPs20ji03LOVWsh/radgE17es5hL+t6lV0eVHrVhsssROWJ
# uz2MXMCt7iw7lFPG9LXKGjsmonn2gotGdHIuEg5JnJMJVmixd5LRlkmgYRZKzhxS
# CwyoGIq0PhaA7Y+VPct5pCHkijcIIDm0nlkK+0KyepolcqGm0T/GYQRMhHJlGOOm
# VQop36wUVUYklUy++vDWeEgEo4s7hxN6mIbf2MSIQ/iIfMZgJxC69oukMUXCrOC3
# SkE/xIkgpfl22MM1itkZ35nNXkMolU1lAgMBAAGjggFOMIIBSjAOBgNVHQ8BAf8E
# BAMCAYYwEAYJKwYBBAGCNxUBBAMCAQAwHQYDVR0OBBYEFH9ZP1Qh2q1P7wXl5qPX
# LQaUEggxMBkGCSsGAQQBgjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAUci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBP
# oE2gS4ZJaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAw
# TgYIKwYBBQUHMAKGQmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMv
# TWljUm9vQ2VyQXV0MjAxMV8yMDExXzAzXzIyLmNydDANBgkqhkiG9w0BAQwFAAOC
# AgEAFJQfOChP7onn6fLIMKrSlN1WYKwDFgAddymOUO3FrM8d7B/W/iQ6DxXsDn7D
# 5W4wMwYeLystcEqfkjz4NURRgazyMu5yRzQh4LqjA4tStTcJh1opExo7nn5PuPBY
# nbu0+THSuVHTe0VTTPVhily/piFrDo3axQ9P4C+Ol5yet+2gTfekICS5xS+cYfSI
# vgn0JksVBVMYVI5QFu/qhnLhsEFEUzG8fvv0hjgkO+lkpV9ty6GkN4vdnd7ya6Q6
# aR9y34aiM1qmxaxBi6OUnyNl6fkuun/diTFnYDLTppOkr/mg5WSfCiDVMNCxtj4w
# PKC5OmHm1DQIt/MNokbbH3UGsFP1QbzsLocuSqLCvH09Io3fDPTmscR9Y75G4qX7
# RTX8AdBPo0I6OEojf39zuFZt0qOHm65YWQE69cZM2ueE1MB05dNNgHK9gTE7zKvK
# /fg8B2qjW88MT/WF5V5uvZGtqa9FSL2RazArA+rDPuf6JGYz4HpgMZHB4S6szWSK
# YBv0VisCzfxgeU+dquXW9bd0auYlOB58DPcOYKdc3Se94g+xL4pcEhbB54JOgAkw
# YTu/9dLeH2pDqeJZAABVDWRQCaXfO5LgyKwKCLYXpigrZYCjUSBcr+Ve8PFWMhVT
# Ql0v4q8J/AUmQN5W4n101cY2L4A7GTQG1h32HHAvfQESWP0xghn7MIIZ9wIBATBu
# MFcxCzAJBgNVBAYTAlVTMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24x
# KDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMjQCEzMAAAIc
# +s3Fm+gvfsQAAAAAAhwwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwG
# CisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZI
# hvcNAQkEMSIEIH1fZxx0mPcp2nsJrNQ0ieT2/SqYAD41D/rsGWRgDqHnMEIGCisG
# AQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEBBQAEggEAElbT6SJ4tLTOZ4wIrB2L
# TwLAWGDKqyBuWeY1RWSCHwF5HnNVVjjlwCPYVTWEpyUtpvv9kxeDlZbYu2N3prBH
# S7a/HRUbeEWRiCi1TxkJgIGLICJ1HBNM1D5zNcz/wr4HxifCAcNCt+2amrZM/gmt
# pk1Njhe06ayUqPx8G6xAY52knnn8Gf3HpUsYiRnZDh5JgZ9EGvh7MZjZ4qmWiXaR
# LlBPysQzPaRQSfw1xjvL1EnkfBHLpMpB4+Oh6z1ziqIAsE3NXdDcJM17gv7VcRU8
# N0x1rMlmwnnbCYoqs9nTOJOTxGe6pYXDLKL9FjJhBc3DFNJbm4fnmfT8bP3L0AY8
# U6GCF60wghepBgorBgEEAYI3AwMBMYIXmTCCF5UGCSqGSIb3DQEHAqCCF4YwgheC
# AgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkEggFFMIIB
# QQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFlAwQCAQUABCD7bOV8TNu8T23U89qg
# 4VGxM0HjJ8kI3WIajy+Ec8V5ogIGajWodJynGBMyMDI2MDcxMTAwNDMyMS42MjVa
# MASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
# bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
# aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0
# ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjo1OTFBLTA1RTAtRDk0NzElMCMG
# A1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEfswggcoMIIFEKAD
# AgECAhMzAAACFI3NI0TuBt9yAAEAAAIUMA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI1MDgxNDE4NDgxOFoXDTI2MTExMzE4
# NDgxOFowgdMxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTAr
# BgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUG
# A1UECxMeblNoaWVsZCBUU1MgRVNOOjU5MUEtMDVFMC1EOTQ3MSUwIwYDVQQDExxN
# aWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOC
# Ag8AMIICCgKCAgEAyU+nWgCUyvfyGP1zTFkLkdgOutXcVteP/0CeXfrF/66chKl4
# /MZDCQ6E8Ur4kqgCxQvef7Lg1gfso1EWWKG6vix1VxtvO1kPGK4PZKmOeoeL68F6
# +Mw2ERPy4BL2vJKf6Lo5Z7X0xkRjtcvfM9T0HDgfHUW6z1CbgQiqrExs2NH27rWp
# UkyTYrMG6TXy39+GdMOTgXyUDiRGVHAy3EqYNw3zSWusn0zedl6a/1DbnXIcvn9F
# aHzd/96EPNBOCd2vOpS0Ck7kgkjVxwOptsWa8I+m+DA43cwlErPaId84GbdGzo3V
# oO7YhCmQIoRab0d8or5Pmyg+VMl8jeoN9SeUxVZpBI/cQ4TXXKlLDkfbzzSQriVi
# QGJGJLtKS3DTVNuBqpjXLdu2p2Yq9ODPqZCoiNBh4CB6X2iLYUSO8tmbUVLMMEeg
# bvHSLXQR88QNICjFoBBDCDydoTo9/TNkq80mO77wDM04tPdvbMmxT01GTod60JJx
# UGmMTgseghdBGjkN+D6GsUpY7ta7hP9PzLrs+Alxu46XT217bBn6EwJsAYAc9C28
# mKRUcoIZWQRb+McoZaSu2EcSzuIlAaNIQNtGlz2PF3foSeGmc/V7gCGs8AHkiKwX
# zJSPftnsH8O/R3pJw2D/2hHE3JzxH2SrLX1FdI7Drw145PkL0hbFL6MVCCkCAwEA
# AaOCAUkwggFFMB0GA1UdDgQWBBTbX/bs1cSpyTYnYuf/Mt9CPNhwGzAfBgNVHSME
# GDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1l
# LVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsG
# AQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01p
# Y3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMB
# Af8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDAN
# BgkqhkiG9w0BAQsFAAOCAgEAP3xp9D4Gu0SH9B+1JH0hswFquINaTT+RjpfEr8Um
# UOeDl4U5uV+i28/eSYXMxgem3yBZywYDyvf4qMXUvbDcllNqRyL2Rv8jSu8wclt/
# VS1+c5cVCJfM+WHvkUr+dCfUlOy9n4exCPX1L6uWwFH5eoFfqPEp3Fw30irMN2So
# nHBK3mB8vDj3D80oJKqe2tatO38yMTiREdC2HD7eVIUWL7d54UtoYxzwkJN1t7gE
# EGosgBpdmwKVYYDO1USWSNmZELglYA4LoVoGDuWbN7mD8VozYBsfkZarOyrJYlF/
# UCDZLB8XaLfrMfMyZTMCOuEuPD4zj8jy/Jt40clrIW04cvLhkhkydBzcrmC2HxeE
# 36gJsh+jzmivS9YvyiPhLkom1FP0DIFr4VlqyXHKagrtnqSF8QyEpqtQS7wS7ZzZ
# F0eZe0fsYD0J1RarbVuDxmWsq45n1vjRdontuGUdmrG2OGeKd8AtiNghfnabVBbg
# pYgcx/eLyW/n40eTbKIlsm0cseyuWvYFyOqQXjoWtL4/sUHxlWIsrjnNarNr+POk
# L8C1jGBCJuvm0UYgjhIaL+XBXavrbOtX9mrZ3y8GQDxWXn3mhqM21ZcGk83xSRqB
# 9ecfGYNRG6g65v635gSzUmBKZWWcDNzwAoxsgEjTFXz6ahfyrBLqshrjJXPKfO+9
# Ar8wggdxMIIFWaADAgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEB
# CwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYD
# VQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAe
# Fw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGm
# TOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/H
# ZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDc
# wUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62A
# W36MEBydUv626GIl3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1w
# jjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCG
# MFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ
# 1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP
# 8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFz
# ymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHz
# NgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3
# xwgVGD94q0W29R6HXtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsG
# AQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/
# LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEG
# DCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYB
# BQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8G
# A1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQw
# VgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9j
# cmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUF
# BwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
# aS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQEL
# BQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfC
# cTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AF
# vonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l
# 9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn
# 8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5m
# O0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyx
# TkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4
# S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9
# y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM
# +Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhw
# RNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDVjCCAj4C
# AQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3Rv
# bjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0
# aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0
# ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVTTjo1OTFBLTA1RTAtRDk0NzElMCMG
# A1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIa
# AxUA2RysX196RXLTwA/P8RFWdUTpUsaggYMwgYCkfjB8MQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
# dGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsFAAIFAO371QEwIhgPMjAyNjA3MTAy
# MDMwNTdaGA8yMDI2MDcxMTIwMzA1N1owdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA
# 7fvVAQIBADAHAgEAAgI5SzAHAgEAAgITKjAKAgUA7f0mgQIBADA2BgorBgEEAYRZ
# CgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0G
# CSqGSIb3DQEBCwUAA4IBAQBSaFBrU+kjok7m1dtCMb/qxW1GPDz3ZJExpk1UjHyb
# H9J/WKXmkNYU7U7E8HqOMUjwJzu9+coMSamMPpbxS+SfLoNckflj8/sEuyJjRhxl
# Ywrab1g29WYWlzF8gfL4LJerUCeRrD+OjcY37Jf6vR6eiQ3eiYDNwor6JnaXBiAS
# rtFjU/pwZh3jnExljxn4kr3EmB4C6WxjJY1SBPH80TpkN+qhWb9lGhgdMzdkQK/C
# ih/bEls017NPTjS7m3FXZCGCxJxtAXandv1W/OtXfM2OASk+QykxgA1nN6YUFIqO
# qmknKxrJWsku/2vUg6PJYcgjAOYfs4i4+dbFWA0XIDb9MYIEDTCCBAkCAQEwgZMw
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAIUjc0jRO4G33IAAQAA
# AhQwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRAB
# BDAvBgkqhkiG9w0BCQQxIgQgod0c2cpOhj38DKu+8BD5Y/mxchpbyHXvj8DG/aR0
# kccwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCA2eKvvWx5bcoi43bRO3+Et
# tQUCvyeD2dbXy/6+0xK+xzCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
# EwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3Nv
# ZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBD
# QSAyMDEwAhMzAAACFI3NI0TuBt9yAAEAAAIUMCIEIJ/tsJAHjNGBd+FQUtRnlq/a
# hkYXLz597HJQ3H9z1k8QMA0GCSqGSIb3DQEBCwUABIICALB2wHQQ35Vg6mHcfYX9
# Z0Szp6/ODnr3eFM+6uAqlF6dqaC1Fxl227/BA+gaThqX/vZW5iPEwOQUHVggLH5j
# CAkwRwhM8GiVEPtMhLqyy7xhCcCa8Ok3H03lUYuyiG2RbJhicRoIMU74RfpFIoHy
# I5HPPai0xtBvsIBU/n1Vqy2FOPT/7W8Cw4iwhApzqw8hQZ4r5Gxy6gGKisE3J9hw
# W5+Tng7LJehhKf47eXjOtNjXdl7B8AiC+wHQ1rPwXSGTkmd3WsKCa2RMZKUBo0lK
# VXJ+vYPpCIAAxIqILHmI7UiZOLj2Mox2AS5bF4O3piTe1qYTi5r7oz7huCkrF03Z
# NkE3HWD94bpzzbQ/gqcmZPIqiQFm0vipKhi2JSVAgsNecgjD5J8rJ3UjpAXDefhR
# JsNZkx4pLQG6JenBBWyuFKI3DbmWNNSu315ao4oDQZfguc+/t4wPS/ihAEfXGgme
# d7biCempBKs8hhYPVUg617EcwksTtWoQCy7E8n1PcBVoGjcHqdeFEkm6j0Wzw9ih
# LVgnvqFxmfU7MKjIL0sMBFJnXfTfdUVEXDzGm2/V0B/OsaLGJnAczNoVMXoPASvU
# yeJqRDU9JKK/6Fr9fvAJSwVtO1S7kC/tcaCWoPDNzdRZ7rhccidzgCGp8FUkBRUw
# hlfZN0hjC3n37fQDetBM2xI8
# SIG # End signature block
