#
# Module manifest for module 'Microsoft.Graph.CloudCommunications'
#
# Generated by: Microsoft Corporation
#
# Generated on: 7/10/2026
#

@{

# Script module or binary module file associated with this manifest.
RootModule = './Microsoft.Graph.CloudCommunications.psm1'

# Version number of this module.
ModuleVersion = '2.38.1'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = '2c67fc60-8c99-463f-9b0c-8a70e4623246'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Graph PowerShell Cmdlets'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Microsoft.Graph.Authentication'; RequiredVersion = '2.38.1'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = './bin/Microsoft.Graph.CloudCommunications.private.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = './Microsoft.Graph.CloudCommunications.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = 'Add-MgCommunicationCallLargeGalleryView', 
               'Clear-MgCommunicationPresence', 
               'Clear-MgCommunicationPresenceAutomaticLocation', 
               'Clear-MgCommunicationPresenceLocation', 
               'Clear-MgCommunicationPresenceUserPreferredPresence', 
               'Clear-MgUserPresence', 'Clear-MgUserPresenceAutomaticLocation', 
               'Clear-MgUserPresenceLocation', 
               'Clear-MgUserPresenceUserPreferredPresence', 
               'Get-MgCommunicationAdhocCall', 'Get-MgCommunicationAdhocCallCount', 
               'Get-MgCommunicationAdhocCallRecording', 
               'Get-MgCommunicationAdhocCallRecordingContent', 
               'Get-MgCommunicationAdhocCallRecordingCount', 
               'Get-MgCommunicationAdhocCallRecordingDelta', 
               'Get-MgCommunicationAdhocCallTranscript', 
               'Get-MgCommunicationAdhocCallTranscriptContent', 
               'Get-MgCommunicationAdhocCallTranscriptCount', 
               'Get-MgCommunicationAdhocCallTranscriptDelta', 
               'Get-MgCommunicationAdhocCallTranscriptMetadataContent', 
               'Get-MgCommunicationCall', 
               'Get-MgCommunicationCallAudioRoutingGroup', 
               'Get-MgCommunicationCallAudioRoutingGroupCount', 
               'Get-MgCommunicationCallContentSharingSession', 
               'Get-MgCommunicationCallContentSharingSessionCount', 
               'Get-MgCommunicationCallCount', 'Get-MgCommunicationCallOperation', 
               'Get-MgCommunicationCallOperationCount', 
               'Get-MgCommunicationCallParticipant', 
               'Get-MgCommunicationCallParticipantCount', 
               'Get-MgCommunicationCallRecord', 
               'Get-MgCommunicationCallRecordCount', 
               'Get-MgCommunicationCallRecordOrganizerV2', 
               'Get-MgCommunicationCallRecordParticipant', 
               'Get-MgCommunicationCallRecordParticipantV2', 
               'Get-MgCommunicationCallRecordSession', 
               'Get-MgCommunicationCallRecordSessionCount', 
               'Get-MgCommunicationCallRecordSessionSegmentCount', 
               'Get-MgCommunicationOnlineMeeting', 
               'Get-MgCommunicationOnlineMeetingAttendanceReport', 
               'Get-MgCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Get-MgCommunicationOnlineMeetingAttendanceReportAttendanceRecordCount', 
               'Get-MgCommunicationOnlineMeetingAttendanceReportCount', 
               'Get-MgCommunicationOnlineMeetingAttendeeReport', 
               'Get-MgCommunicationOnlineMeetingConversation', 
               'Get-MgCommunicationOnlineMeetingConversationCount', 
               'Get-MgCommunicationOnlineMeetingConversationMessage', 
               'Get-MgCommunicationOnlineMeetingConversationMessageConversation', 
               'Get-MgCommunicationOnlineMeetingConversationMessageCount', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReaction', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReactionCount', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReply', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReplyConversation', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReplyCount', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReplyReaction', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReplyReactionCount', 
               'Get-MgCommunicationOnlineMeetingConversationMessageReplyTo', 
               'Get-MgCommunicationOnlineMeetingConversationOnlineMeeting', 
               'Get-MgCommunicationOnlineMeetingConversationOnlineMeetingAttendeeReport', 
               'Get-MgCommunicationOnlineMeetingConversationStarter', 
               'Get-MgCommunicationOnlineMeetingConversationStarterConversation', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReaction', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReactionCount', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReply', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReplyConversation', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReplyCount', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReplyReaction', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReplyReactionCount', 
               'Get-MgCommunicationOnlineMeetingConversationStarterReplyTo', 
               'Get-MgCommunicationOnlineMeetingCount', 
               'Get-MgCommunicationOnlineMeetingMessage', 
               'Get-MgCommunicationOnlineMeetingRecording', 
               'Get-MgCommunicationOnlineMeetingRecordingContent', 
               'Get-MgCommunicationOnlineMeetingRecordingCount', 
               'Get-MgCommunicationOnlineMeetingRecordingDelta', 
               'Get-MgCommunicationOnlineMeetingTranscript', 
               'Get-MgCommunicationOnlineMeetingTranscriptContent', 
               'Get-MgCommunicationOnlineMeetingTranscriptCount', 
               'Get-MgCommunicationOnlineMeetingTranscriptDelta', 
               'Get-MgCommunicationOnlineMeetingTranscriptMetadataContent', 
               'Get-MgCommunicationOnlineMeetingVirtualAppointmentJoinWebUrl', 
               'Get-MgCommunicationPresence', 
               'Get-MgCommunicationPresenceByUserId', 
               'Get-MgCommunicationPresenceCount', 'Get-MgUserOnlineMeeting', 
               'Get-MgUserOnlineMeetingAttendanceReport', 
               'Get-MgUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Get-MgUserOnlineMeetingAttendanceReportAttendanceRecordCount', 
               'Get-MgUserOnlineMeetingAttendanceReportCount', 
               'Get-MgUserOnlineMeetingAttendeeReport', 
               'Get-MgUserOnlineMeetingCount', 'Get-MgUserOnlineMeetingRecording', 
               'Get-MgUserOnlineMeetingRecordingContent', 
               'Get-MgUserOnlineMeetingRecordingCount', 
               'Get-MgUserOnlineMeetingRecordingDelta', 
               'Get-MgUserOnlineMeetingTranscript', 
               'Get-MgUserOnlineMeetingTranscriptContent', 
               'Get-MgUserOnlineMeetingTranscriptCount', 
               'Get-MgUserOnlineMeetingTranscriptDelta', 
               'Get-MgUserOnlineMeetingTranscriptMetadataContent', 
               'Get-MgUserOnlineMeetingVirtualAppointmentJoinWebUrl', 
               'Get-MgUserPresence', 'Invoke-MgAnswerCommunicationCall', 
               'Invoke-MgCreateOrGetCommunicationOnlineMeeting', 
               'Invoke-MgInviteCommunicationCallParticipant', 
               'Invoke-MgKeepCommunicationCallAlive', 
               'Invoke-MgLogCommunicationCallTeleconferenceDeviceQuality', 
               'Invoke-MgMuteCommunicationCall', 
               'Invoke-MgMuteCommunicationCallParticipant', 
               'Invoke-MgPlayCommunicationCallPrompt', 
               'Invoke-MgRecordCommunicationCallResponse', 
               'Invoke-MgRedirectCommunicationCall', 
               'Invoke-MgRejectCommunicationCall', 
               'Invoke-MgSubscribeCommunicationCallToTone', 
               'Invoke-MgUnmuteCommunicationCall', 'Move-MgCommunicationCall', 
               'New-MgCommunicationAdhocCall', 
               'New-MgCommunicationAdhocCallRecording', 
               'New-MgCommunicationAdhocCallTranscript', 'New-MgCommunicationCall', 
               'New-MgCommunicationCallAudioRoutingGroup', 
               'New-MgCommunicationCallContentSharingSession', 
               'New-MgCommunicationCallOperation', 
               'New-MgCommunicationCallParticipant', 
               'New-MgCommunicationCallRecordParticipantV2', 
               'New-MgCommunicationCallRecordSession', 
               'New-MgCommunicationOnlineMeeting', 
               'New-MgCommunicationOnlineMeetingAttendanceReport', 
               'New-MgCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'New-MgCommunicationOnlineMeetingConversation', 
               'New-MgCommunicationOnlineMeetingConversationMessage', 
               'New-MgCommunicationOnlineMeetingConversationMessageReaction', 
               'New-MgCommunicationOnlineMeetingConversationMessageReply', 
               'New-MgCommunicationOnlineMeetingConversationMessageReplyReaction', 
               'New-MgCommunicationOnlineMeetingConversationStarterReaction', 
               'New-MgCommunicationOnlineMeetingConversationStarterReply', 
               'New-MgCommunicationOnlineMeetingConversationStarterReplyReaction', 
               'New-MgCommunicationOnlineMeetingRecording', 
               'New-MgCommunicationOnlineMeetingTranscript', 
               'New-MgCommunicationPresence', 'New-MgUserOnlineMeeting', 
               'New-MgUserOnlineMeetingAttendanceReport', 
               'New-MgUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'New-MgUserOnlineMeetingRecording', 
               'New-MgUserOnlineMeetingTranscript', 
               'Remove-MgCommunicationAdhocCall', 
               'Remove-MgCommunicationAdhocCallRecording', 
               'Remove-MgCommunicationAdhocCallRecordingContent', 
               'Remove-MgCommunicationAdhocCallTranscript', 
               'Remove-MgCommunicationAdhocCallTranscriptContent', 
               'Remove-MgCommunicationAdhocCallTranscriptMetadataContent', 
               'Remove-MgCommunicationCall', 
               'Remove-MgCommunicationCallAudioRoutingGroup', 
               'Remove-MgCommunicationCallContentSharingSession', 
               'Remove-MgCommunicationCallOperation', 
               'Remove-MgCommunicationCallParticipant', 
               'Remove-MgCommunicationCallRecordOrganizerV2', 
               'Remove-MgCommunicationCallRecordParticipantV2', 
               'Remove-MgCommunicationCallRecordSession', 
               'Remove-MgCommunicationOnlineMeeting', 
               'Remove-MgCommunicationOnlineMeetingAttendanceReport', 
               'Remove-MgCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Remove-MgCommunicationOnlineMeetingAttendeeReport', 
               'Remove-MgCommunicationOnlineMeetingConversation', 
               'Remove-MgCommunicationOnlineMeetingConversationMessage', 
               'Remove-MgCommunicationOnlineMeetingConversationMessageReaction', 
               'Remove-MgCommunicationOnlineMeetingConversationMessageReply', 
               'Remove-MgCommunicationOnlineMeetingConversationMessageReplyReaction', 
               'Remove-MgCommunicationOnlineMeetingConversationOnlineMeetingAttendeeReport', 
               'Remove-MgCommunicationOnlineMeetingConversationStarter', 
               'Remove-MgCommunicationOnlineMeetingConversationStarterReaction', 
               'Remove-MgCommunicationOnlineMeetingConversationStarterReply', 
               'Remove-MgCommunicationOnlineMeetingConversationStarterReplyReaction', 
               'Remove-MgCommunicationOnlineMeetingRecording', 
               'Remove-MgCommunicationOnlineMeetingRecordingContent', 
               'Remove-MgCommunicationOnlineMeetingTranscript', 
               'Remove-MgCommunicationOnlineMeetingTranscriptContent', 
               'Remove-MgCommunicationOnlineMeetingTranscriptMetadataContent', 
               'Remove-MgCommunicationPresence', 'Remove-MgUserOnlineMeeting', 
               'Remove-MgUserOnlineMeetingAttendanceReport', 
               'Remove-MgUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Remove-MgUserOnlineMeetingAttendeeReport', 
               'Remove-MgUserOnlineMeetingRecording', 
               'Remove-MgUserOnlineMeetingRecordingContent', 
               'Remove-MgUserOnlineMeetingTranscript', 
               'Remove-MgUserOnlineMeetingTranscriptContent', 
               'Remove-MgUserOnlineMeetingTranscriptMetadataContent', 
               'Remove-MgUserPresence', 
               'Rename-MgCommunicationCallScreenSharingRole', 
               'Send-MgCommunicationCallDtmfTone', 
               'Send-MgCommunicationOnlineMeetingVirtualAppointmentReminderSm', 
               'Send-MgCommunicationOnlineMeetingVirtualAppointmentSm', 
               'Send-MgUserOnlineMeetingVirtualAppointmentReminderSm', 
               'Send-MgUserOnlineMeetingVirtualAppointmentSm', 
               'Set-MgCommunicationAdhocCallRecordingContent', 
               'Set-MgCommunicationAdhocCallTranscriptContent', 
               'Set-MgCommunicationAdhocCallTranscriptMetadataContent', 
               'Set-MgCommunicationOnlineMeetingAttendeeReport', 
               'Set-MgCommunicationOnlineMeetingConversationOnlineMeetingAttendeeReport', 
               'Set-MgCommunicationOnlineMeetingRecordingContent', 
               'Set-MgCommunicationOnlineMeetingTranscriptContent', 
               'Set-MgCommunicationOnlineMeetingTranscriptMetadataContent', 
               'Set-MgCommunicationPresence', 
               'Set-MgCommunicationPresenceAutomaticLocation', 
               'Set-MgCommunicationPresenceManualLocation', 
               'Set-MgCommunicationPresenceStatusMessage', 
               'Set-MgCommunicationPresenceUserPreferredPresence', 
               'Set-MgUserOnlineMeetingAttendeeReport', 
               'Set-MgUserOnlineMeetingRecordingContent', 
               'Set-MgUserOnlineMeetingTranscriptContent', 
               'Set-MgUserOnlineMeetingTranscriptMetadataContent', 
               'Set-MgUserPresence', 'Set-MgUserPresenceAutomaticLocation', 
               'Set-MgUserPresenceManualLocation', 
               'Set-MgUserPresenceStatusMessage', 
               'Set-MgUserPresenceUserPreferredPresence', 
               'Start-MgCommunicationCallParticipantHoldMusic', 
               'Stop-MgCommunicationCallMediaProcessing', 
               'Stop-MgCommunicationCallParticipantHoldMusic', 
               'Update-MgCommunicationAdhocCall', 
               'Update-MgCommunicationAdhocCallRecording', 
               'Update-MgCommunicationAdhocCallTranscript', 
               'Update-MgCommunicationCallAudioRoutingGroup', 
               'Update-MgCommunicationCallContentSharingSession', 
               'Update-MgCommunicationCallOperation', 
               'Update-MgCommunicationCallParticipant', 
               'Update-MgCommunicationCallRecordingStatus', 
               'Update-MgCommunicationCallRecordOrganizerV2', 
               'Update-MgCommunicationCallRecordParticipantV2', 
               'Update-MgCommunicationCallRecordSession', 
               'Update-MgCommunicationOnlineMeeting', 
               'Update-MgCommunicationOnlineMeetingAttendanceReport', 
               'Update-MgCommunicationOnlineMeetingAttendanceReportAttendanceRecord', 
               'Update-MgCommunicationOnlineMeetingConversation', 
               'Update-MgCommunicationOnlineMeetingConversationMessage', 
               'Update-MgCommunicationOnlineMeetingConversationMessageReaction', 
               'Update-MgCommunicationOnlineMeetingConversationMessageReply', 
               'Update-MgCommunicationOnlineMeetingConversationMessageReplyReaction', 
               'Update-MgCommunicationOnlineMeetingConversationStarter', 
               'Update-MgCommunicationOnlineMeetingConversationStarterReaction', 
               'Update-MgCommunicationOnlineMeetingConversationStarterReply', 
               'Update-MgCommunicationOnlineMeetingConversationStarterReplyReaction', 
               'Update-MgCommunicationOnlineMeetingRecording', 
               'Update-MgCommunicationOnlineMeetingTranscript', 
               'Update-MgCommunicationPresence', 'Update-MgUserOnlineMeeting', 
               'Update-MgUserOnlineMeetingAttendanceReport', 
               'Update-MgUserOnlineMeetingAttendanceReportAttendanceRecord', 
               'Update-MgUserOnlineMeetingRecording', 
               'Update-MgUserOnlineMeetingTranscript', 'Update-MgUserPresence'

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-MgAllUserOnlineMeetingRecording', 
               'Get-MgAllUserOnlineMeetingTranscript'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Microsoft','Office365','Graph','PowerShell','PSModule','PSIncludes_Cmdlet'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/devservicesagreement'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/microsoftgraph/msgraph-sdk-powershell'

        # A URL to an icon representing this module.
        IconUri = 'https://raw.githubusercontent.com/microsoftgraph/msgraph-sdk-powershell/dev/docs/images/graph_color256.png'

        # ReleaseNotes of this module
        ReleaseNotes = 'See https://aka.ms/GraphPowerShell-Release.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIInRgYJKoZIhvcNAQcCoIInNzCCJzMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCB7NiiCDXB8kabh
# wWvMBIK1sbaUX5RVbc0HEaB47+1/zqCCDLowggX1MIID3aADAgECAhMzAAACHU0Z
# yE7XD1dIAAAAAAIdMA0GCSqGSIb3DQEBCwUAMFcxCzAJBgNVBAYTAlVTMR4wHAYD
# VQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBD
# b2RlIFNpZ25pbmcgUENBIDIwMjQwHhcNMjYwNDE2MTg1OTQzWhcNMjcwNDE1MTg1
# OTQzWjB0MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYD
# VQQDExVNaWNyb3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IB
# DwAwggEKAoIBAQDQvewXxx9gZZFC6Ys1WBay8BJ8kGA4JQnH5CMafqOASlTpK9H8
# o5ZXTXt0caVQTNMUPt445wXYD+dFtaKWTwDn1I52oUSrC9vJin1Gsqt+zyKJL5Dg
# 3eQXbQNR61DmMy20GLTIO3SFed9Rfi/ophgCLGFLDR3r0KvHjwMb/jYWS0celV/4
# Lz27LfAekm8v9E5IXaeiXbAUYZKK090n4CVl3JBtbN+9DtI9SNu/yjvozW52/u7R
# X/Ttpa/KDlpuokZ+Zcbvmtd9ur9gFLvZzh41o9MsE/clQtdaFWGvuo6Jua/ntpgk
# ey3E5/vBFe+MJPG6phdnuo6r57ZudCudiI1bAgMBAAGjggGbMIIBlzAOBgNVHQ8B
# Af8EBAMCB4AwHwYDVR0lBBgwFgYKKwYBBAGCN0wIAQYIKwYBBQUHAwMwHQYDVR0O
# BBYEFH6QuMwqcPG0hQlQ6c5jCtTTLrVeMEUGA1UdEQQ+MDykOjA4MR4wHAYDVQQL
# ExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xFjAUBgNVBAUTDTIzMDAxMis1MDc1NTkw
# HwYDVR0jBBgwFoAUf1k/VCHarU/vBeXmo9ctBpQSCDEwYAYDVR0fBFkwVzBVoFOg
# UYZPaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwvTWljcm9zb2Z0
# JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNybDBtBggrBgEFBQcBAQRh
# MF8wXQYIKwYBBQUHMAKGUWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y2VydHMvTWljcm9zb2Z0JTIwQ29kZSUyMFNpZ25pbmclMjBQQ0ElMjAyMDI0LmNy
# dDAMBgNVHRMBAf8EAjAAMA0GCSqGSIb3DQEBCwUAA4ICAQBKTbYOjzwTG/DXGaz9
# s6+fQeaTtDcFmMY+5UyVFCyj7Pv+5i37qfX8lSL/tBIfYQfWsMuBQlfZurJD6r4H
# VJ2CeH+1fgiq8dcHdVKoZ3Sa2qXoX3cq9iS8cVb06B7+5/XJ7I0OxHH9fDsvJ3T3
# w5V/ZtAIFmLrl+P0CtG+92uzRsn0nTbdFjOkLMLWPLAU3THohKRlSEMgFJpPkm5n
# 5UAZ35xX6FWCrDLsSKb555bTifwa8mJBwdlof0bmfYidH+dxZ1FdDxvLnNl9zeKs
# A4kejaaIqqIPguhwAti5Ql7BlTNoJNwxCvBmqW2MQLnCkYN/VVUsR3V2x/rcTNzo
# Bf/Z/SpROvdaA2ZOOd1uioXJt3tdLQ7vHpqpib0KfWr/FWXW10q38VxfCnRQBqzb
# SuztR7nEMuzX7Ck+B/XaPDXd1qh72+QYyB0Z2VzWmO9zsnb9Uq/dwu8LGeQqnyu6
# 7SDGACvnXii2fb9+US492VTnXSnFKyqwgzUyFMtZK1/sHYTv6bG4TtQUygQxTN+Z
# V+aJIlKO2MqZ7bKrAnOzS9m6NgoTdWOq11bTOZwKlIEV/EhV9SWkDmdpR/hPPT2v
# 6TEj4F8PT/zHjRezIU5c/DGlt/VhY/pK0XkJtEyMmmS1BMtjU/rqBZVMIm3dnxQs
# /TBByr+Cf8Z1r7aifQVQ+WSqzjCCBr0wggSloAMCAQICEzMAAAA5O7Y3Gb8GHWcA
# AAAAADkwDQYJKoZIhvcNAQEMBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDExMB4XDTI0MDgwODIwNTQxOFoXDTM2MDMyMjIyMTMwNFow
# VzELMAkGA1UEBhMCVVMxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEo
# MCYGA1UEAxMfTWljcm9zb2Z0IENvZGUgU2lnbmluZyBQQ0EgMjAyNDCCAiIwDQYJ
# KoZIhvcNAQEBBQADggIPADCCAgoCggIBANgBnB7jOMeqlRYHNa265v4IY9fH8TKh
# emHfPINe1gpLaV3dhg324WwH06LcHbpnsBukCDNitryo0dtS/EW6I/yEL/bLSY8h
# KpbfQuWusBPr9qazYcDxCW/qnjb5JsI1s8bNOg3bVATvQVL4tcf03aTycsz8QeCd
# M0l/yHRObJ9QqazM1r6VPEOJ7LL+uEEb73w6QCuhs89a1uv1zerOYMnsneRRwCbp
# yW11IcggU0cRKDDq1pjVJzIbIF6+oiXXbReOsgeI8zu1FyQfK0fVkaya8SmVHQ/t
# Of23mZ4W9k0Ri22QW9p3UgSC5OUDktKxxcCmGL6tXLfOGSWHIIV4YrTJTT6PNty5
# REojHJuZHArkF9VnHTERWoTjAzfI3kP+5b4alUdhgAZ7ttOu1bVnXfHaqPYl2rPs
# 20ji03LOVWsh/radgE17es5hL+t6lV0eVHrVhsssROWJuz2MXMCt7iw7lFPG9LXK
# Gjsmonn2gotGdHIuEg5JnJMJVmixd5LRlkmgYRZKzhxSCwyoGIq0PhaA7Y+VPct5
# pCHkijcIIDm0nlkK+0KyepolcqGm0T/GYQRMhHJlGOOmVQop36wUVUYklUy++vDW
# eEgEo4s7hxN6mIbf2MSIQ/iIfMZgJxC69oukMUXCrOC3SkE/xIkgpfl22MM1itkZ
# 35nNXkMolU1lAgMBAAGjggFOMIIBSjAOBgNVHQ8BAf8EBAMCAYYwEAYJKwYBBAGC
# NxUBBAMCAQAwHQYDVR0OBBYEFH9ZP1Qh2q1P7wXl5qPXLQaUEggxMBkGCSsGAQQB
# gjcUAgQMHgoAUwB1AGIAQwBBMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# ci06AjGQQ7kUBU7h6qfHMdEjiTQwWgYDVR0fBFMwUTBPoE2gS4ZJaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNybDBeBggrBgEFBQcBAQRSMFAwTgYIKwYBBQUHMAKGQmh0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWljUm9vQ2VyQXV0MjAx
# MV8yMDExXzAzXzIyLmNydDANBgkqhkiG9w0BAQwFAAOCAgEAFJQfOChP7onn6fLI
# MKrSlN1WYKwDFgAddymOUO3FrM8d7B/W/iQ6DxXsDn7D5W4wMwYeLystcEqfkjz4
# NURRgazyMu5yRzQh4LqjA4tStTcJh1opExo7nn5PuPBYnbu0+THSuVHTe0VTTPVh
# ily/piFrDo3axQ9P4C+Ol5yet+2gTfekICS5xS+cYfSIvgn0JksVBVMYVI5QFu/q
# hnLhsEFEUzG8fvv0hjgkO+lkpV9ty6GkN4vdnd7ya6Q6aR9y34aiM1qmxaxBi6OU
# nyNl6fkuun/diTFnYDLTppOkr/mg5WSfCiDVMNCxtj4wPKC5OmHm1DQIt/MNokbb
# H3UGsFP1QbzsLocuSqLCvH09Io3fDPTmscR9Y75G4qX7RTX8AdBPo0I6OEojf39z
# uFZt0qOHm65YWQE69cZM2ueE1MB05dNNgHK9gTE7zKvK/fg8B2qjW88MT/WF5V5u
# vZGtqa9FSL2RazArA+rDPuf6JGYz4HpgMZHB4S6szWSKYBv0VisCzfxgeU+dquXW
# 9bd0auYlOB58DPcOYKdc3Se94g+xL4pcEhbB54JOgAkwYTu/9dLeH2pDqeJZAABV
# DWRQCaXfO5LgyKwKCLYXpigrZYCjUSBcr+Ve8PFWMhVTQl0v4q8J/AUmQN5W4n10
# 1cY2L4A7GTQG1h32HHAvfQESWP0xghniMIIZ3gIBATBuMFcxCzAJBgNVBAYTAlVT
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jv
# c29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMjQCEzMAAAIdTRnITtcPV0gAAAAAAh0w
# DQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYK
# KwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIFkQhlM/
# ZG/9G5PzWeGPAMp+G1EWyYzQL8w7oHVS+x/EMEIGCisGAQQBgjcCAQwxNDAyoBSA
# EgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20w
# DQYJKoZIhvcNAQEBBQAEggEAfTPG3/ZQVdpAFSq3dKgDoGNsYu65lDDHHDt5BMZs
# YIiow2XhpMFhW5kV3LVBAdRtL9uD3ZTn0NmW70rsnMJEIU3V2stbgYThoR0eGA9G
# eb2Dxz+TN7q66aitrE9D1C8EC2h6NwAmlf+OXbIEepPExHbA3lDE+aHIaYZF1JD6
# LaaRNWQL5YY5KOeDHsTzhVZ5WupE10rHxmxdeQ8J9YPmno4Sw0eyYfE84MQFmf34
# tiMNhy8uVWjiOQUytcfdBDezxS1B1CpduuV3BZLoYlvjnW5M9AiiRrFBm1N1npF0
# EjuSiqE/nsjFgWd9/fBVFaADO8yBR/4V8JakCJJe+X6216GCF5QwgheQBgorBgEE
# AYI3AwMBMYIXgDCCF3wGCSqGSIb3DQEHAqCCF20wghdpAgEDMQ8wDQYJYIZIAWUD
# BAIBBQAwggFSBgsqhkiG9w0BCRABBKCCAUEEggE9MIIBOQIBAQYKKwYBBAGEWQoD
# ATAxMA0GCWCGSAFlAwQCAQUABCAyRBn7twb/LvMiTHR46BtHVy/90KD4UDbo+Au9
# T7hnOQIGajF5TZGtGBMyMDI2MDcxMTAwNDIzNS43ODJaMASAAgH0oIHRpIHOMIHL
# MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVk
# bW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxN
# aWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRT
# UyBFU046N0YwMC0wNUUwLUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFNlcnZpY2WgghHqMIIHIDCCBQigAwIBAgITMwAAAh6jrKRuOW98SQABAAAC
# HjANBgkqhkiG9w0BAQsFADB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGlu
# Z3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBv
# cmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAe
# Fw0yNjAyMTkxOTM5NDlaFw0yNzA1MTcxOTM5NDlaMIHLMQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSUwIwYDVQQLExxNaWNyb3NvZnQgQW1lcmlj
# YSBPcGVyYXRpb25zMScwJQYDVQQLEx5uU2hpZWxkIFRTUyBFU046N0YwMC0wNUUw
# LUQ5NDcxJTAjBgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIi
# MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCl0TjtbDwsR7Fe8ac6ol5s1zht
# Tqd2AWpchQhLp9G5mmSM23N5fyQGCQ1D06rOA3PgXKF+76vXvOCs2VsLv1owj4mH
# EyEqiq8GJ5yC+/QNYRpZPA8e7OgekzDO6S/4vy/jTMYbp3rhuFiKKCzTWOQtdFcF
# +D0k369I7pm/E07SyNMGkuNd5lj5SJ91UqFuZfjMB6cQ2wh77mtiRUVdj53yjdNq
# j+GQl+Yaz29Bjrzn7U1ln+JpLlnb0xdGmZoIPKZbwBVcWtyL4uyhML7SSTmiOfWX
# U+g+yNl0CdoLGL8LtWHEi8FsuTPeSdSqmeMrvLaEmibTVTS4vQQY8NPnb6uI5y6i
# NV9vBFcm8LU/lDTjGTqPa7UBT4gdf5Jm3wYrfCFZ4P/j5MoqT0JONca50jt4TGI9
# 0SihXaDEYqk23S0IJZ3UkUpukDRTjK713BIykffxyBqMeQqfO0zvWfUx7BrmUpug
# Qcw99+DxLl2gf+uQEpRmnlbrVJ9dvW9ds4fqEPN2jG0QwF1PBSglNcV1SpqZKitQ
# gBGSwu/82AKztoCHwYRHRNwzwTVe/1KNTvmqAd4Uges4ywOH02haagT8wYY8OdWd
# jKn3k052w+kmc0UC0F+iVXTGZIMxvo9iBZQoXehzRtWJ/VOtKvCyS3csKzN7rStW
# JwjSWz6dtOf0l+ytLQIDAQABo4IBSTCCAUUwHQYDVR0OBBYEFOYKFprqBB0JZmJc
# FC4cPPmeF4JkMB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1Ud
# HwRYMFYwVKBSoFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3Js
# L01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggr
# BgEFBQcBAQRgMF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNv
# bS9wa2lvcHMvY2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIw
# MTAoMSkuY3J0MAwGA1UdEwEB/wQCMAAwFgYDVR0lAQH/BAwwCgYIKwYBBQUHAwgw
# DgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4ICAQCkoZB5NnJVFb5wKejR
# onk518a2TBNYpKcBMtfL6BS0ARaABOMGYLlPNuhI1HwmelP9hX3oq3TaEm/cDkkz
# NQAzDedPgoRI2R7+8poNSWvHXEAs7SZODm9x7KqlBkNZM9ex4XY1yNmVOAmWDjRr
# 7jKjaiQbntf7EC4GNikxGGaVWOjfYt3Q9X0r/Ks8KBlbzDR9zjA/TCctR4co1WpU
# 1ZRLFrB9bl8dRxsbnyT2qQ41E7dT12R30eIGUziEs5GN+26V/ovXOi20dJiM13hY
# Wvy1NNJAhkKOlLB1ONund6ffhPdUcHWsu8V+lR0aakMV64HqDbLumZrCNwUofVx3
# xMk8F4tCYJtQxLTywc30sZAD1S2sC1959x6KixA+p41FLUl8g64oHy3bfYnH5xd4
# JOBgQoaqndGjcctxr+8EknjhKyrgAzrTcKLJbUezgoye8brCLJ+y6PAoEjpXRkSY
# AU8wfQ3YWRck6ALwoV7Uin8+rpGQSbXhF6c1dTFakXmChClud4IADY/t6JRkJ+06
# FzL+jDd8KLV8Qj77JfiuTiPIG5G/xlnGoZFcX+yyBtDvzZE48d+Y+HYUd/cvhH1F
# Kl7AH+5AyotqJSFmvM/BuYRx2B20asVXilV2k2JbNO3LGCz3Q+dpElzwsfJrka1N
# /getma7fWpowsNvoIaEQvjad8TCCB3EwggVZoAMCAQICEzMAAAAVxedrngKbSZkA
# AAAAABUwDQYJKoZIhvcNAQELBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpX
# YXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQg
# Q29ycG9yYXRpb24xMjAwBgNVBAMTKU1pY3Jvc29mdCBSb290IENlcnRpZmljYXRl
# IEF1dGhvcml0eSAyMDEwMB4XDTIxMDkzMDE4MjIyNVoXDTMwMDkzMDE4MzIyNVow
# fDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1Jl
# ZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMd
# TWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTAwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQDk4aZM57RyIQt5osvXJHm9DtWC0/3unAcH0qlsTnXIyjVX
# 9gF/bErg4r25PhdgM/9cT8dm95VTcVrifkpa/rg2Z4VGIwy1jRPPdzLAEBjoYH1q
# UoNEt6aORmsHFPPFdvWGUNzBRMhxXFExN6AKOG6N7dcP2CZTfDlhAnrEqv1yaa8d
# q6z2Nr41JmTamDu6GnszrYBbfowQHJ1S/rboYiXcag/PXfT+jlPP1uyFVk3v3byN
# pOORj7I5LFGc6XBpDco2LXCOMcg1KL3jtIckw+DJj361VI/c+gVVmG1oO5pGve2k
# rnopN6zL64NF50ZuyjLVwIYwXE8s4mKyzbnijYjklqwBSru+cakXW2dg3viSkR4d
# Pf0gz3N9QZpGdc3EXzTdEonW/aUgfX782Z5F37ZyL9t9X4C626p+Nuw2TPYrbqgS
# Uei/BQOj0XOmTTd0lBw0gg/wEPK3Rxjtp+iZfD9M269ewvPV2HM9Q07BMzlMjgK8
# QmguEOqEUUbi0b1qGFphAXPKZ6Je1yh2AuIzGHLXpyDwwvoSCtdjbwzJNmSLW6Cm
# gyFdXzB0kZSU2LlQ+QuJYfM2BjUYhEfb3BvR/bLUHMVr9lxSUV0S2yW6r1AFemzF
# ER1y7435UsSFF5PAPBXbGjfHCBUYP3irRbb1Hode2o+eFnJpxq57t7c+auIurQID
# AQABo4IB3TCCAdkwEgYJKwYBBAGCNxUBBAUCAwEAATAjBgkrBgEEAYI3FQIEFgQU
# KqdS/mTEmr6CkTxGNSnPEP8vBO4wHQYDVR0OBBYEFJ+nFV0AXmJdg/Tl0mWnG1M1
# GelyMFwGA1UdIARVMFMwUQYMKwYBBAGCN0yDfQEBMEEwPwYIKwYBBQUHAgEWM2h0
# dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvRG9jcy9SZXBvc2l0b3J5Lmh0
# bTATBgNVHSUEDDAKBggrBgEFBQcDCDAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMA
# QTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBTV9lbL
# j+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1p
# Y3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3
# Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEwLTA2LTIz
# LmNydDANBgkqhkiG9w0BAQsFAAOCAgEAnVV9/Cqt4SwfZwExJFvhnnJL/Klv6lwU
# tj5OR2R4sQaTlz0xM7U518JxNj/aZGx80HU5bbsPMeTCj/ts0aGUGCLu6WZnOlNN
# 3Zi6th542DYunKmCVgADsAW+iehp4LoJ7nvfam++Kctu2D9IdQHZGN5tggz1bSNU
# 5HhTdSRXud2f8449xvNo32X2pFaq95W2KFUn0CS9QKC/GbYSEhFdPSfgQJY4rPf5
# KYnDvBewVIVCs/wMnosZiefwC2qBwoEZQhlSdYo2wh3DYXMuLGt7bj8sCXgU6ZGy
# qVvfSaN0DLzskYDSPeZKPmY7T7uG+jIa2Zb0j/aRAfbOxnT99kxybxCrdTDFNLB6
# 2FD+CljdQDzHVG2dY3RILLFORy3BFARxv2T5JL5zbcqOCb2zAVdJVGTZc9d/HltE
# AY5aGZFrDZ+kKNxnGSgkujhLmm77IVRrakURR6nxt67I6IleT53S0Ex2tVdUCbFp
# AUR+fKFhbHP+CrvsQWY9af3LwUFJfn6Tvsv4O+S3Fb+0zj6lMVGEvL8CwYKiexcd
# FYmNcP7ntdAoGokLjzbaukz5m/8K6TT4JDVnK+ANuOaMmdbhIurwJ0I9JZTmdHRb
# atGePu1+oDEzfbzL6Xu/OHBE0ZDxyKs6ijoIYn/ZcGNTTY3ugm2lBRDBcQZqELQd
# VTNYs6FwZvKhggNNMIICNQIBATCB+aGB0aSBzjCByzELMAkGA1UEBhMCVVMxEzAR
# BgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1p
# Y3Jvc29mdCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2Eg
# T3BlcmF0aW9uczEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjdGMDAtMDVFMC1E
# OTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNloiMKAQEw
# BwYFKw4DAhoDFQCD/QNkKDIW4VIF7j3oi2qbrR0a/6CBgzCBgKR+MHwxCzAJBgNV
# BAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4w
# HAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29m
# dCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0GCSqGSIb3DQEBCwUAAgUA7fuYVzAiGA8y
# MDI2MDcxMDE2MTIwN1oYDzIwMjYwNzExMTYxMjA3WjB0MDoGCisGAQQBhFkKBAEx
# LDAqMAoCBQDt+5hXAgEAMAcCAQACAhMVMAcCAQACAhIYMAoCBQDt/OnXAgEAMDYG
# CisGAQQBhFkKBAIxKDAmMAwGCisGAQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEA
# AgMBhqAwDQYJKoZIhvcNAQELBQADggEBABeN7/1fsssYN/OVu+qmCAioSLPvnNfY
# gK6J7bsDAnyq+c3Zl6w5/EjnJLWRwoOO0ZbqttuCfUSxej7ozrv1b6DrWh4v92Q+
# ZVSglbYWDBkKfh4QDZD7oeR/JVLNR8ENEAUUnq5e3oomkJCBZ8KBVccqrHAnT6QL
# j7kvyEB2U+NkJgpM+7UZbE1OAa4bwpKXgOWvdqNfCWD3YnWFurWmpavxyDKzkGl7
# i3kp7NcZzBBeoUIED08fNKFvqaMj6Rc4XjmkcbOqqbDjNgMsTpRg9e2hcwy+0GCW
# aUoex51l8S7/f1uuFKndol6WAJN0nVwAwxIsQHb8u+paGbL/XBA/z70xggQNMIIE
# CQIBATCBkzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYw
# JAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAh6jrKRu
# OW98SQABAAACHjANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqG
# SIb3DQEJEAEEMC8GCSqGSIb3DQEJBDEiBCDRz2CFGstvzC6PP3Y0UddtdohN+2xq
# NUSnA37Tn6lfKzCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EIC+BXWrz9geM
# gM8Bvn8bqxHjhHXJ29EBizITIw0B9vOCMIGYMIGApH4wfDELMAkGA1UEBhMCVVMx
# EzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoT
# FU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUt
# U3RhbXAgUENBIDIwMTACEzMAAAIeo6ykbjlvfEkAAQAAAh4wIgQgI/TjOg0ToGLb
# QpeE1kD52f6E5lYhJUQU49RzOVtCeYUwDQYJKoZIhvcNAQELBQAEggIAlbQXjSvK
# DTDpgpZ489mYjii9ozvl3ojAXMsKplKqCym6aLoumyAJDhALnCR3NDs+5SqOp9G/
# XH05oSardfzKR1pXHb5YLu16BeWw5FIFSalSkbFtdzBeXNViN7e+rues+D/715rl
# wOy6m4gK2+rVqMcEYe3ujQROonAtReyrAUXABOT2uwmQ8RytZX1QZbx0/QMSKmDD
# NHhDItNwoHx1GlMNmNwhECuYEiBTCgAlKuCp+oSfpxaYce1Hh2FdV6SSWqLdBMGd
# 1J5qZ0chNidpKbw7B9JEZqLw3v4tZyNO5OEeV2KK7Cv4k/34xVSZK0rvJyDC7P2k
# Cv2V239st7EI9/HxJTMR0ZVqRNB+MmInvwhitSRF+2cmVEv0rEJur/pxA0gEkfzV
# iijNp28g+Qy3hvmCPAHmz9PcTPsjXul40lPktdHwj807pOn42TGqZsQwArYAVIcn
# +sbGugm7hk2GnIqzWuQ3bRae5fQau4OrphrYIPTe4avsFBoWqOLFYZVWolr8XUl+
# 4hOuM6JIKw0jt48+8iGfHGrgKLn9G+AKRe2ug3v4ul6xFl5e7lu2/6ehOICJ1gVB
# 5tIizS1MIat6JmoX8DYQWtV92ycuwiR8BVrULdBh+/WUgZ5ZLp8MlJAGgP/w+hPc
# gsWQ/qskXjVhzRPs1BjGcuIvRaKcggSqsvU=
# SIG # End signature block
